//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Shared {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceBreadCrumb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceBreadCrumb() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Shared.ResourceBreadCrumb", typeof(ResourceBreadCrumb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterar Senha.
        /// </summary>
        public static string Action_alterarsenha {
            get {
                return ResourceManager.GetString("Action_alterarsenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bloqueio.
        /// </summary>
        public static string Action_bloqueiomodulo {
            get {
                return ResourceManager.GetString("Action_bloqueiomodulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Documento Obsoleto.
        /// </summary>
        public static string Action_conteudodocumentoobsoleto {
            get {
                return ResourceManager.GetString("Action_conteudodocumentoobsoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criar.
        /// </summary>
        public static string Action_criar {
            get {
                return ResourceManager.GetString("Action_criar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Documentos em Aprovação.
        /// </summary>
        public static string Action_documentosaprovacao {
            get {
                return ResourceManager.GetString("Action_documentosaprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Documentos Aprovados.
        /// </summary>
        public static string Action_documentosaprovados {
            get {
                return ResourceManager.GetString("Action_documentosaprovados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Documentos em Elaboração.
        /// </summary>
        public static string Action_documentoselaboracao {
            get {
                return ResourceManager.GetString("Action_documentoselaboracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Documentos em Verificação.
        /// </summary>
        public static string Action_documentosverificacao {
            get {
                return ResourceManager.GetString("Action_documentosverificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        public static string Action_editar {
            get {
                return ResourceManager.GetString("Action_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Emissão de Documento.
        /// </summary>
        public static string Action_emissaodocumento {
            get {
                return ResourceManager.GetString("Action_emissaodocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fluxo.
        /// </summary>
        public static string Action_fluxo {
            get {
                return ResourceManager.GetString("Action_fluxo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imprimir.
        /// </summary>
        public static string Action_imprimir {
            get {
                return ResourceManager.GetString("Action_imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedores.
        /// </summary>
        public static string Action_IndexFornecedores {
            get {
                return ResourceManager.GetString("Action_IndexFornecedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Meus Dados.
        /// </summary>
        public static string Action_meusdados {
            get {
                return ResourceManager.GetString("Action_meusdados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recursos.
        /// </summary>
        public static string Action_recursos {
            get {
                return ResourceManager.GetString("Action_recursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro.
        /// </summary>
        public static string Action_registro {
            get {
                return ResourceManager.GetString("Action_registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Riscos.
        /// </summary>
        public static string Action_riscos {
            get {
                return ResourceManager.GetString("Action_riscos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rotina.
        /// </summary>
        public static string Action_rotina {
            get {
                return ResourceManager.GetString("Action_rotina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ação Corretiva.
        /// </summary>
        public static string Controller_acaocorretiva {
            get {
                return ResourceManager.GetString("Controller_acaocorretiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Análise Crítica.
        /// </summary>
        public static string Controller_analisecritica {
            get {
                return ResourceManager.GetString("Controller_analisecritica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Auditoria.
        /// </summary>
        public static string Controller_auditoria {
            get {
                return ResourceManager.GetString("Controller_auditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Calibração.
        /// </summary>
        public static string Controller_calibracao {
            get {
                return ResourceManager.GetString("Controller_calibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo.
        /// </summary>
        public static string Controller_cargo {
            get {
                return ResourceManager.GetString("Controller_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente.
        /// </summary>
        public static string Controller_cliente {
            get {
                return ResourceManager.GetString("Controller_cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ControlDoc.
        /// </summary>
        public static string Controller_controldoc {
            get {
                return ResourceManager.GetString("Controller_controldoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Qualificação de Fornecedores.
        /// </summary>
        public static string Controller_fornecedor {
            get {
                return ResourceManager.GetString("Controller_fornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gestão de Risco.
        /// </summary>
        public static string Controller_gestaoderisco {
            get {
                return ResourceManager.GetString("Controller_gestaoderisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro.
        /// </summary>
        public static string Controller_home {
            get {
                return ResourceManager.GetString("Controller_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Indicadores.
        /// </summary>
        public static string Controller_indicador {
            get {
                return ResourceManager.GetString("Controller_indicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instrumentos.
        /// </summary>
        public static string Controller_instrumento {
            get {
                return ResourceManager.GetString("Controller_instrumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não Conformidade.
        /// </summary>
        public static string Controller_naoconformidade {
            get {
                return ResourceManager.GetString("Controller_naoconformidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Norma.
        /// </summary>
        public static string Controller_norma {
            get {
                return ResourceManager.GetString("Controller_norma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plai.
        /// </summary>
        public static string Controller_plai {
            get {
                return ResourceManager.GetString("Controller_plai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processo.
        /// </summary>
        public static string Controller_processo {
            get {
                return ResourceManager.GetString("Controller_processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Site.
        /// </summary>
        public static string Controller_site {
            get {
                return ResourceManager.GetString("Controller_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário.
        /// </summary>
        public static string Controller_usuario {
            get {
                return ResourceManager.GetString("Controller_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processo.
        /// </summary>
        public static string Processo {
            get {
                return ResourceManager.GetString("Processo", resourceCulture);
            }
        }
    }
}
