//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceLabel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLabel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Shared.ResourceLabel", typeof(ResourceLabel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2017.
        /// </summary>
        public static string Label_ano_2017 {
            get {
                return ResourceManager.GetString("Label_ano_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018.
        /// </summary>
        public static string Label_ano_2018 {
            get {
                return ResourceManager.GetString("Label_ano_2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019.
        /// </summary>
        public static string Label_ano_2019 {
            get {
                return ResourceManager.GetString("Label_ano_2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020.
        /// </summary>
        public static string Label_ano_2020 {
            get {
                return ResourceManager.GetString("Label_ano_2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string Label_dropdown_name_select {
            get {
                return ResourceManager.GetString("Label_dropdown_name_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        public static string Label_mes_Abr {
            get {
                return ResourceManager.GetString("Label_mes_Abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        public static string Label_mes_Ago {
            get {
                return ResourceManager.GetString("Label_mes_Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezembro.
        /// </summary>
        public static string Label_mes_Dez {
            get {
                return ResourceManager.GetString("Label_mes_Dez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fevereiro.
        /// </summary>
        public static string Label_mes_Fev {
            get {
                return ResourceManager.GetString("Label_mes_Fev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Janeiro.
        /// </summary>
        public static string Label_mes_Jan {
            get {
                return ResourceManager.GetString("Label_mes_Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julho.
        /// </summary>
        public static string Label_mes_Jul {
            get {
                return ResourceManager.GetString("Label_mes_Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junho.
        /// </summary>
        public static string Label_mes_Jun {
            get {
                return ResourceManager.GetString("Label_mes_Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maio.
        /// </summary>
        public static string Label_mes_Mai {
            get {
                return ResourceManager.GetString("Label_mes_Mai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Março.
        /// </summary>
        public static string Label_mes_Mar {
            get {
                return ResourceManager.GetString("Label_mes_Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novembro.
        /// </summary>
        public static string Label_mes_Nov {
            get {
                return ResourceManager.GetString("Label_mes_Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outubro.
        /// </summary>
        public static string Label_mes_Out {
            get {
                return ResourceManager.GetString("Label_mes_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setembro.
        /// </summary>
        public static string Label_mes_Set {
            get {
                return ResourceManager.GetString("Label_mes_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abr.
        /// </summary>
        public static string Label_mes_short_Abr {
            get {
                return ResourceManager.GetString("Label_mes_short_Abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ago.
        /// </summary>
        public static string Label_mes_short_Ago {
            get {
                return ResourceManager.GetString("Label_mes_short_Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dez.
        /// </summary>
        public static string Label_mes_short_Dez {
            get {
                return ResourceManager.GetString("Label_mes_short_Dez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fev.
        /// </summary>
        public static string Label_mes_short_Fev {
            get {
                return ResourceManager.GetString("Label_mes_short_Fev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string Label_mes_short_Jan {
            get {
                return ResourceManager.GetString("Label_mes_short_Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        public static string Label_mes_short_Jul {
            get {
                return ResourceManager.GetString("Label_mes_short_Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string Label_mes_short_Jun {
            get {
                return ResourceManager.GetString("Label_mes_short_Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai.
        /// </summary>
        public static string Label_mes_short_Mai {
            get {
                return ResourceManager.GetString("Label_mes_short_Mai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string Label_mes_short_Mar {
            get {
                return ResourceManager.GetString("Label_mes_short_Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string Label_mes_short_Nov {
            get {
                return ResourceManager.GetString("Label_mes_short_Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string Label_mes_short_Out {
            get {
                return ResourceManager.GetString("Label_mes_short_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Label_mes_short_Set {
            get {
                return ResourceManager.GetString("Label_mes_short_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação.
        /// </summary>
        public static string Label_perfil_Acao {
            get {
                return ResourceManager.GetString("Label_perfil_Acao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string Label_perfil_Administrador {
            get {
                return ResourceManager.GetString("Label_perfil_Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaborador.
        /// </summary>
        public static string Label_perfil_Colaborador {
            get {
                return ResourceManager.GetString("Label_perfil_Colaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordenador.
        /// </summary>
        public static string Label_perfil_Coordenador {
            get {
                return ResourceManager.GetString("Label_perfil_Coordenador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Label_perfil_Status {
            get {
                return ResourceManager.GetString("Label_perfil_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suporte.
        /// </summary>
        public static string Label_perfil_Suporte {
            get {
                return ResourceManager.GetString("Label_perfil_Suporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Label_radio_Nao {
            get {
                return ResourceManager.GetString("Label_radio_Nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Label_radio_Sim {
            get {
                return ResourceManager.GetString("Label_radio_Sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar todos.
        /// </summary>
        public static string Label_select_All {
            get {
                return ResourceManager.GetString("Label_select_All", resourceCulture);
            }
        }
    }
}
