//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceButtons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceButtons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Shared.ResourceButtons", typeof(ResourceButtons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso Negado.
        /// </summary>
        public static string btn_lbl_acesso_negado {
            get {
                return ResourceManager.GetString("btn_lbl_acesso_negado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string btn_lbl_adicionar {
            get {
                return ResourceManager.GetString("btn_lbl_adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        public static string btn_lbl_alterar {
            get {
                return ResourceManager.GetString("btn_lbl_alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexar.
        /// </summary>
        public static string btn_lbl_anexar {
            get {
                return ResourceManager.GetString("btn_lbl_anexar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativar.
        /// </summary>
        public static string btn_lbl_ativar {
            get {
                return ResourceManager.GetString("btn_lbl_ativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string btn_lbl_ativo {
            get {
                return ResourceManager.GetString("btn_lbl_ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        public static string btn_lbl_bloqueado {
            get {
                return ResourceManager.GetString("btn_lbl_bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string btn_lbl_cancelar {
            get {
                return ResourceManager.GetString("btn_lbl_cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string btn_lbl_cargo {
            get {
                return ResourceManager.GetString("btn_lbl_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativar.
        /// </summary>
        public static string btn_lbl_desativar {
            get {
                return ResourceManager.GetString("btn_lbl_desativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloqueado.
        /// </summary>
        public static string btn_lbl_desbloqueado {
            get {
                return ResourceManager.GetString("btn_lbl_desbloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destravar.
        /// </summary>
        public static string btn_lbl_destravar {
            get {
                return ResourceManager.GetString("btn_lbl_destravar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Alteração.
        /// </summary>
        public static string btn_lbl_dt_alteracao {
            get {
                return ResourceManager.GetString("btn_lbl_dt_alteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Alteração - Não informada.
        /// </summary>
        public static string btn_lbl_dt_alteracao_nao_informada {
            get {
                return ResourceManager.GetString("btn_lbl_dt_alteracao_nao_informada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Inclusão.
        /// </summary>
        public static string btn_lbl_dt_inclusao {
            get {
                return ResourceManager.GetString("btn_lbl_dt_inclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Inclusão - Não informada.
        /// </summary>
        public static string btn_lbl_dt_inclusao_nao_informada {
            get {
                return ResourceManager.GetString("btn_lbl_dt_inclusao_nao_informada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string btn_lbl_editar {
            get {
                return ResourceManager.GetString("btn_lbl_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string btn_lbl_entrar {
            get {
                return ResourceManager.GetString("btn_lbl_entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string btn_lbl_enviar {
            get {
                return ResourceManager.GetString("btn_lbl_enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string btn_lbl_excluir {
            get {
                return ResourceManager.GetString("btn_lbl_excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string btn_lbl_fechar {
            get {
                return ResourceManager.GetString("btn_lbl_fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string btn_lbl_imprimir {
            get {
                return ResourceManager.GetString("btn_lbl_imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        public static string btn_lbl_inativo {
            get {
                return ResourceManager.GetString("btn_lbl_inativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string btn_lbl_nao {
            get {
                return ResourceManager.GetString("btn_lbl_nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não receber e-mail.
        /// </summary>
        public static string btn_lbl_nao_receber_email {
            get {
                return ResourceManager.GetString("btn_lbl_nao_receber_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plai.
        /// </summary>
        public static string btn_lbl_plai {
            get {
                return ResourceManager.GetString("btn_lbl_plai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receber e-mail.
        /// </summary>
        public static string btn_lbl_receber_email {
            get {
                return ResourceManager.GetString("btn_lbl_receber_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string btn_lbl_salvar {
            get {
                return ResourceManager.GetString("btn_lbl_salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string btn_lbl_sim {
            get {
                return ResourceManager.GetString("btn_lbl_sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string btn_lbl_site {
            get {
                return ResourceManager.GetString("btn_lbl_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string btn_lbl_usuario {
            get {
                return ResourceManager.GetString("btn_lbl_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        public static string btn_lbl_visualizar {
            get {
                return ResourceManager.GetString("btn_lbl_visualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string btn_lbl_voltar {
            get {
                return ResourceManager.GetString("btn_lbl_voltar", resourceCulture);
            }
        }
    }
}
