//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceBreadCrumb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceBreadCrumb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Shared.ResourceBreadCrumb", typeof(ResourceBreadCrumb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Senha.
        /// </summary>
        public static string Action_alterarsenha {
            get {
                return ResourceManager.GetString("Action_alterarsenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueio.
        /// </summary>
        public static string Action_bloqueiomodulo {
            get {
                return ResourceManager.GetString("Action_bloqueiomodulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Obsoleto.
        /// </summary>
        public static string Action_conteudodocumentoobsoleto {
            get {
                return ResourceManager.GetString("Action_conteudodocumentoobsoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar.
        /// </summary>
        public static string Action_criar {
            get {
                return ResourceManager.GetString("Action_criar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos em Aprovação.
        /// </summary>
        public static string Action_documentosaprovacao {
            get {
                return ResourceManager.GetString("Action_documentosaprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos Aprovados.
        /// </summary>
        public static string Action_documentosaprovados {
            get {
                return ResourceManager.GetString("Action_documentosaprovados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos em Elaboração.
        /// </summary>
        public static string Action_documentoselaboracao {
            get {
                return ResourceManager.GetString("Action_documentoselaboracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos Obsoletos.
        /// </summary>
        public static string Action_documentosobsoletos {
            get {
                return ResourceManager.GetString("Action_documentosobsoletos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos em Revisão.
        /// </summary>
        public static string Action_documentosrevisao {
            get {
                return ResourceManager.GetString("Action_documentosrevisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos em Verificação.
        /// </summary>
        public static string Action_documentosverificacao {
            get {
                return ResourceManager.GetString("Action_documentosverificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Action_editar {
            get {
                return ResourceManager.GetString("Action_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emissão de Documento.
        /// </summary>
        public static string Action_emissaodocumento {
            get {
                return ResourceManager.GetString("Action_emissaodocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluxo.
        /// </summary>
        public static string Action_fluxo {
            get {
                return ResourceManager.GetString("Action_fluxo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string Action_imprimir {
            get {
                return ResourceManager.GetString("Action_imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedores.
        /// </summary>
        public static string Action_IndexFornecedores {
            get {
                return ResourceManager.GetString("Action_IndexFornecedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Dados.
        /// </summary>
        public static string Action_meusdados {
            get {
                return ResourceManager.GetString("Action_meusdados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos.
        /// </summary>
        public static string Action_recursos {
            get {
                return ResourceManager.GetString("Action_recursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string Action_registro {
            get {
                return ResourceManager.GetString("Action_registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riscos.
        /// </summary>
        public static string Action_riscos {
            get {
                return ResourceManager.GetString("Action_riscos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotina.
        /// </summary>
        public static string Action_rotina {
            get {
                return ResourceManager.GetString("Action_rotina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação Corretiva.
        /// </summary>
        public static string Controller_acaocorretiva {
            get {
                return ResourceManager.GetString("Controller_acaocorretiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise Crítica.
        /// </summary>
        public static string Controller_analisecritica {
            get {
                return ResourceManager.GetString("Controller_analisecritica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoria.
        /// </summary>
        public static string Controller_auditoria {
            get {
                return ResourceManager.GetString("Controller_auditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibração.
        /// </summary>
        public static string Controller_calibracao {
            get {
                return ResourceManager.GetString("Controller_calibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string Controller_cargo {
            get {
                return ResourceManager.GetString("Controller_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Controller_cliente {
            get {
                return ResourceManager.GetString("Controller_cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlDoc.
        /// </summary>
        public static string Controller_controldoc {
            get {
                return ResourceManager.GetString("Controller_controldoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualificação de Fornecedores.
        /// </summary>
        public static string Controller_fornecedor {
            get {
                return ResourceManager.GetString("Controller_fornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Risco.
        /// </summary>
        public static string Controller_gestaoderisco {
            get {
                return ResourceManager.GetString("Controller_gestaoderisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Melhoria.
        /// </summary>
        public static string Controller_gestaomelhoria {
            get {
                return ResourceManager.GetString("Controller_gestaomelhoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string Controller_home {
            get {
                return ResourceManager.GetString("Controller_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicadores.
        /// </summary>
        public static string Controller_indicador {
            get {
                return ResourceManager.GetString("Controller_indicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumentos.
        /// </summary>
        public static string Controller_instrumento {
            get {
                return ResourceManager.GetString("Controller_instrumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licença.
        /// </summary>
        public static string Controller_licenca {
            get {
                return ResourceManager.GetString("Controller_licenca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Conformidade.
        /// </summary>
        public static string Controller_naoconformidade {
            get {
                return ResourceManager.GetString("Controller_naoconformidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norma.
        /// </summary>
        public static string Controller_norma {
            get {
                return ResourceManager.GetString("Controller_norma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plai.
        /// </summary>
        public static string Controller_plai {
            get {
                return ResourceManager.GetString("Controller_plai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string Controller_processo {
            get {
                return ResourceManager.GetString("Controller_processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Controller_site {
            get {
                return ResourceManager.GetString("Controller_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Controller_usuario {
            get {
                return ResourceManager.GetString("Controller_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenca.
        /// </summary>
        public static string Licenca {
            get {
                return ResourceManager.GetString("Licenca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string Processo {
            get {
                return ResourceManager.GetString("Processo", resourceCulture);
            }
        }
    }
}
