//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Usuario {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceUsuario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUsuario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Usuario.ResourceUsuario", typeof(ResourceUsuario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite sua senha atual.
        /// </summary>
        public static string AlterarSenha_lbl_placeholder_Senha_atual {
            get {
                return ResourceManager.GetString("AlterarSenha_lbl_placeholder_Senha_atual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme a nova senha.
        /// </summary>
        public static string AlterarSenha_lbl_placeholder_Senha_confirma {
            get {
                return ResourceManager.GetString("AlterarSenha_lbl_placeholder_Senha_confirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite sua nova senha.
        /// </summary>
        public static string AlterarSenha_lbl_placeholder_Senha_nova {
            get {
                return ResourceManager.GetString("AlterarSenha_lbl_placeholder_Senha_nova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Atual.
        /// </summary>
        public static string AlterarSenha_lbl_Senha_atual {
            get {
                return ResourceManager.GetString("AlterarSenha_lbl_Senha_atual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir Senha.
        /// </summary>
        public static string AlterarSenha_lbl_Senha_confirma {
            get {
                return ResourceManager.GetString("AlterarSenha_lbl_Senha_confirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Senha.
        /// </summary>
        public static string AlterarSenha_lbl_Senha_nova {
            get {
                return ResourceManager.GetString("AlterarSenha_lbl_Senha_nova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Senha.
        /// </summary>
        public static string AlterarSenha_lbl_titulo {
            get {
                return ResourceManager.GetString("AlterarSenha_lbl_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Senha Atual é obrigatório..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_atual {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_atual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Confirmar Senha é obrigatório..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_confirma {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_confirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nova Senha deve ser igual ao Confirmar Senha..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_confirma_equals {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_confirma_equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Confirma Senha deve ter no mínimo 6 caracteres..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_confirma_minlength {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_confirma_minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Nova Senha não pode ser igual a Atual..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_notequals {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_notequals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nova Senha é obrigatório..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_nova {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_nova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nova Senha deve ter no mínimo 6 caracteres..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_nova_minlength {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_nova_minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha deve ser forte ou muito forte..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_nova_strong_pwd {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_nova_strong_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha Atual não confere..
        /// </summary>
        public static string AlterarSenha_msg_Senha_error_equals {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_Senha_error_equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração de Senha efetuada com sucesso..
        /// </summary>
        public static string AlterarSenha_msg_Senha_valid_change {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_Senha_valid_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha expirou, altere para continuar navegando..
        /// </summary>
        public static string AlteraSenha_lbl_SuaSenhaExpirou {
            get {
                return ResourceManager.GetString("AlteraSenha_lbl_SuaSenhaExpirou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção: para excluir esse usuario você deve cadastrar primeiro outro com o mesmo cargo para migrar suas pendências..
        /// </summary>
        public static string AtencaoParaExcluirEsseUsuarioVoceDevePrimeiroCadastrarOutroComOMesmoCargo {
            get {
                return ResourceManager.GetString("AtencaoParaExcluirEsseUsuarioVoceDevePrimeiroCadastrarOutroComOMesmoCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessario escolher um modulo..
        /// </summary>
        public static string Cliente_msg_required_SiteFuncionalidade {
            get {
                return ResourceManager.GetString("Cliente_msg_required_SiteFuncionalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Usuario_lbl_Acoes {
            get {
                return ResourceManager.GetString("Usuario_lbl_Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo?.
        /// </summary>
        public static string Usuario_lbl_Acoes_ativo {
            get {
                return ResourceManager.GetString("Usuario_lbl_Acoes_ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado?.
        /// </summary>
        public static string Usuario_lbl_Acoes_bloqueado {
            get {
                return ResourceManager.GetString("Usuario_lbl_Acoes_bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartilhado?.
        /// </summary>
        public static string Usuario_lbl_Acoes_compartilhado {
            get {
                return ResourceManager.GetString("Usuario_lbl_Acoes_compartilhado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recebe E-mail.
        /// </summary>
        public static string Usuario_lbl_Acoes_recebe_email {
            get {
                return ResourceManager.GetString("Usuario_lbl_Acoes_recebe_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Usuário.
        /// </summary>
        public static string Usuario_lbl_Cadastro_titulo {
            get {
                return ResourceManager.GetString("Usuario_lbl_Cadastro_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Usuario_lbl_Cliente {
            get {
                return ResourceManager.GetString("Usuario_lbl_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string Usuario_lbl_CPF {
            get {
                return ResourceManager.GetString("Usuario_lbl_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Expiração.
        /// </summary>
        public static string Usuario_lbl_DataExpiracao {
            get {
                return ResourceManager.GetString("Usuario_lbl_DataExpiracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Usuario_lbl_Email {
            get {
                return ResourceManager.GetString("Usuario_lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto do Usuário.
        /// </summary>
        public static string Usuario_lbl_Foto {
            get {
                return ResourceManager.GetString("Usuario_lbl_Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Usuario_lbl_Nome {
            get {
                return ResourceManager.GetString("Usuario_lbl_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Usuário.
        /// </summary>
        public static string Usuario_lbl_novo_usuario {
            get {
                return ResourceManager.GetString("Usuario_lbl_novo_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Usuario_lbl_Perfil {
            get {
                return ResourceManager.GetString("Usuario_lbl_Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___.___.___-__.
        /// </summary>
        public static string Usuario_lbl_placeholder_CPF {
            get {
                return ResourceManager.GetString("Usuario_lbl_placeholder_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __/__/____.
        /// </summary>
        public static string Usuario_lbl_placeholder_DataExpiracao {
            get {
                return ResourceManager.GetString("Usuario_lbl_placeholder_DataExpiracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o e-mail..
        /// </summary>
        public static string Usuario_lbl_placeholder_Email {
            get {
                return ResourceManager.GetString("Usuario_lbl_placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça o Upload de sua foto..
        /// </summary>
        public static string Usuario_lbl_placeholder_Foto {
            get {
                return ResourceManager.GetString("Usuario_lbl_placeholder_Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o nome do responsável.
        /// </summary>
        public static string Usuario_lbl_placeholder_Responsavel {
            get {
                return ResourceManager.GetString("Usuario_lbl_placeholder_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha o sexo..
        /// </summary>
        public static string Usuario_lbl_placeholder_Sexo {
            get {
                return ResourceManager.GetString("Usuario_lbl_placeholder_Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        public static string Usuario_lbl_Responsavel {
            get {
                return ResourceManager.GetString("Usuario_lbl_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Usuario_lbl_Sexo {
            get {
                return ResourceManager.GetString("Usuario_lbl_Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feminino.
        /// </summary>
        public static string Usuario_lbl_Sexo_feminino {
            get {
                return ResourceManager.GetString("Usuario_lbl_Sexo_feminino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string Usuario_lbl_Sexo_masculino {
            get {
                return ResourceManager.GetString("Usuario_lbl_Sexo_masculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Usuário.
        /// </summary>
        public static string Usuario_lbl_titulo {
            get {
                return ResourceManager.GetString("Usuario_lbl_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário criado com sucesso..
        /// </summary>
        public static string Usuario_msg_criar_valid {
            get {
                return ResourceManager.GetString("Usuario_msg_criar_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário editado com sucesso..
        /// </summary>
        public static string Usuario_msg_editar_valid {
            get {
                return ResourceManager.GetString("Usuario_msg_editar_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao enviar e-mail de novo usuário..
        /// </summary>
        public static string Usuario_msg_ErroEnviarEmail {
            get {
                return ResourceManager.GetString("Usuario_msg_ErroEnviarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário excluido com sucesso..
        /// </summary>
        public static string Usuario_msg_exluir {
            get {
                return ResourceManager.GetString("Usuario_msg_exluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Ativar o usuário?.
        /// </summary>
        public static string Usuario_msg_icone_ativo_ativar {
            get {
                return ResourceManager.GetString("Usuario_msg_icone_ativo_ativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Inativar o usuário?.
        /// </summary>
        public static string Usuario_msg_icone_ativo_inativar {
            get {
                return ResourceManager.GetString("Usuario_msg_icone_ativo_inativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status modificado com sucesso..
        /// </summary>
        public static string Usuario_msg_icone_ativo_valid {
            get {
                return ResourceManager.GetString("Usuario_msg_icone_ativo_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Bloquear o usuário?.
        /// </summary>
        public static string Usuario_msg_icone_bloqueia_ativar {
            get {
                return ResourceManager.GetString("Usuario_msg_icone_bloqueia_ativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Desbloquear o usuário?.
        /// </summary>
        public static string Usuario_msg_icone_bloqueia_inativar {
            get {
                return ResourceManager.GetString("Usuario_msg_icone_bloqueia_inativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status modificado com sucesso..
        /// </summary>
        public static string Usuario_msg_icone_bloqueia_valid {
            get {
                return ResourceManager.GetString("Usuario_msg_icone_bloqueia_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo não receber e-mail?.
        /// </summary>
        public static string Usuario_msg_icone_email_ativar {
            get {
                return ResourceManager.GetString("Usuario_msg_icone_email_ativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo receber e-mail?.
        /// </summary>
        public static string Usuario_msg_icone_email_inativar {
            get {
                return ResourceManager.GetString("Usuario_msg_icone_email_inativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status modificado com sucesso..
        /// </summary>
        public static string Usuario_msg_icone_email_valid {
            get {
                return ResourceManager.GetString("Usuario_msg_icone_email_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Excluir o usuário?.
        /// </summary>
        public static string Usuario_msg_icone_excluir {
            get {
                return ResourceManager.GetString("Usuario_msg_icone_excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id do Usuário não encontrado no sistema..
        /// </summary>
        public static string Usuario_msg_not_found_IdUsuario {
            get {
                return ResourceManager.GetString("Usuario_msg_not_found_IdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha uma ou mais ações..
        /// </summary>
        public static string Usuario_msg_required_Acoes {
            get {
                return ResourceManager.GetString("Usuario_msg_required_Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF é obrigatório..
        /// </summary>
        public static string Usuario_msg_required_CPF {
            get {
                return ResourceManager.GetString("Usuario_msg_required_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite um CPF válido..
        /// </summary>
        public static string Usuario_msg_required_CPF_isvalid {
            get {
                return ResourceManager.GetString("Usuario_msg_required_CPF_isvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Data de Expiração é obrigatório..
        /// </summary>
        public static string Usuario_msg_required_DataExpiracao {
            get {
                return ResourceManager.GetString("Usuario_msg_required_DataExpiracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo E-mail é obrigatório..
        /// </summary>
        public static string Usuario_msg_required_Email {
            get {
                return ResourceManager.GetString("Usuario_msg_required_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato de e-mail não é válido..
        /// </summary>
        public static string Usuario_msg_required_email_error_format {
            get {
                return ResourceManager.GetString("Usuario_msg_required_email_error_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo E-mail deve ter no máximo 60 caracteres..
        /// </summary>
        public static string Usuario_msg_required_Email_maxlength {
            get {
                return ResourceManager.GetString("Usuario_msg_required_Email_maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Foto é obrigatório..
        /// </summary>
        public static string Usuario_msg_required_Foto {
            get {
                return ResourceManager.GetString("Usuario_msg_required_Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Foto só aceita extensões do tipo &quot;.jpg&quot;, &quot;.png&quot; e &quot;.gif&quot;.
        /// </summary>
        public static string Usuario_msg_required_Foto_extension {
            get {
                return ResourceManager.GetString("Usuario_msg_required_Foto_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Campo CPF deve conter 11 caracteres..
        /// </summary>
        public static string Usuario_msg_required_maxlength_Usuario {
            get {
                return ResourceManager.GetString("Usuario_msg_required_maxlength_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Perfil é obrigatório..
        /// </summary>
        public static string Usuario_msg_required_Perfil {
            get {
                return ResourceManager.GetString("Usuario_msg_required_Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Responsável é obrigatório..
        /// </summary>
        public static string Usuario_msg_required_Responsavel {
            get {
                return ResourceManager.GetString("Usuario_msg_required_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Responsável deve ter no máximo 60 caracteres..
        /// </summary>
        public static string Usuario_msg_required_Responsavel_maxlength {
            get {
                return ResourceManager.GetString("Usuario_msg_required_Responsavel_maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Sexo é obrigatório..
        /// </summary>
        public static string Usuario_msg_required_Sexo {
            get {
                return ResourceManager.GetString("Usuario_msg_required_Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha deve ser diferente das @UltimasSenhas@ últimas senhas.
        /// </summary>
        public static string Usuario_Senha_NovaSenhaDeveSerDiferente {
            get {
                return ResourceManager.GetString("Usuario_Senha_NovaSenhaDeveSerDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários para migração de pendências..
        /// </summary>
        public static string UsuarioMigracaoPendencias {
            get {
                return ResourceManager.GetString("UsuarioMigracaoPendencias", resourceCulture);
            }
        }
    }
}
