//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Site {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceSite_US_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSite_US_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Site.ResourceSite_US-EN", typeof(ResourceSite_US_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Site_lbl_Cliente {
            get {
                return ResourceManager.GetString("Site_lbl_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        public static string Site_lbl_Cnpj {
            get {
                return ResourceManager.GetString("Site_lbl_Cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha os sites.
        /// </summary>
        public static string Site_lbl_Escolha_site {
            get {
                return ResourceManager.GetString("Site_lbl_Escolha_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frase.
        /// </summary>
        public static string Site_lbl_Frase {
            get {
                return ResourceManager.GetString("Site_lbl_Frase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logotipo do Site.
        /// </summary>
        public static string Site_lbl_Logo {
            get {
                return ResourceManager.GetString("Site_lbl_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Fantasia.
        /// </summary>
        public static string Site_lbl_Nome {
            get {
                return ResourceManager.GetString("Site_lbl_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Site.
        /// </summary>
        public static string Site_lbl_novo_site {
            get {
                return ResourceManager.GetString("Site_lbl_novo_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações.
        /// </summary>
        public static string Site_lbl_Observacoes {
            get {
                return ResourceManager.GetString("Site_lbl_Observacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o CNPJ.
        /// </summary>
        public static string Site_lbl_placeholder_Cnpj {
            get {
                return ResourceManager.GetString("Site_lbl_placeholder_Cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o slogan.
        /// </summary>
        public static string Site_lbl_placeholder_Frase {
            get {
                return ResourceManager.GetString("Site_lbl_placeholder_Frase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça o upload do logo.
        /// </summary>
        public static string Site_lbl_placeholder_Logo {
            get {
                return ResourceManager.GetString("Site_lbl_placeholder_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o nome fantasia da empresa.
        /// </summary>
        public static string Site_lbl_placeholder_Nome {
            get {
                return ResourceManager.GetString("Site_lbl_placeholder_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite algumas observações.
        /// </summary>
        public static string Site_lbl_placeholder_Observacoes {
            get {
                return ResourceManager.GetString("Site_lbl_placeholder_Observacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a razão social da empresa.
        /// </summary>
        public static string Site_lbl_placeholder_Razao_Social {
            get {
                return ResourceManager.GetString("Site_lbl_placeholder_Razao_Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão Social.
        /// </summary>
        public static string Site_lbl_Razao_Social {
            get {
                return ResourceManager.GetString("Site_lbl_Razao_Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites.
        /// </summary>
        public static string Site_lbl_Sites {
            get {
                return ResourceManager.GetString("Site_lbl_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Site.
        /// </summary>
        public static string Site_lbl_titulo {
            get {
                return ResourceManager.GetString("Site_lbl_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Site_lbl_titulo_site {
            get {
                return ResourceManager.GetString("Site_lbl_titulo_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site salvo com sucesso..
        /// </summary>
        public static string Site_msg_criar_valid {
            get {
                return ResourceManager.GetString("Site_msg_criar_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site excluido com sucesso..
        /// </summary>
        public static string Site_msg_exluir {
            get {
                return ResourceManager.GetString("Site_msg_exluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Ativar o site?.
        /// </summary>
        public static string Site_msg_icone_ativo_ativar {
            get {
                return ResourceManager.GetString("Site_msg_icone_ativo_ativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Inativar o site?.
        /// </summary>
        public static string Site_msg_icone_ativo_inativar {
            get {
                return ResourceManager.GetString("Site_msg_icone_ativo_inativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status modificado com sucesso..
        /// </summary>
        public static string Site_msg_icone_ativo_valid {
            get {
                return ResourceManager.GetString("Site_msg_icone_ativo_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Excluir o site?.
        /// </summary>
        public static string Site_msg_icone_excluir {
            get {
                return ResourceManager.GetString("Site_msg_icone_excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Id do Site é invalido..
        /// </summary>
        public static string Site_msg_not_found_IdSite {
            get {
                return ResourceManager.GetString("Site_msg_not_found_IdSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durante a criação de um novo Site é necessario que o mesmo esteja Ativo..
        /// </summary>
        public static string Site_msg_required_Ativo {
            get {
                return ResourceManager.GetString("Site_msg_required_Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CNPJ é obrigatório..
        /// </summary>
        public static string Site_msg_required_Cnpj {
            get {
                return ResourceManager.GetString("Site_msg_required_Cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite um CNPJ válido..
        /// </summary>
        public static string Site_msg_required_Cnpj_isvalid {
            get {
                return ResourceManager.GetString("Site_msg_required_Cnpj_isvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensão do Logo do Site é obrigatória..
        /// </summary>
        public static string Site_msg_required_ExtensaoLogo {
            get {
                return ResourceManager.GetString("Site_msg_required_ExtensaoLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Frase é obrigatório..
        /// </summary>
        public static string Site_msg_required_Frase {
            get {
                return ResourceManager.GetString("Site_msg_required_Frase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Logo do Site é obrigatório..
        /// </summary>
        public static string Site_msg_required_Logo {
            get {
                return ResourceManager.GetString("Site_msg_required_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Logo só aceita extensões do tipo &quot;.jpg&quot;, &quot;.png&quot; e &quot;.gif&quot;.
        /// </summary>
        public static string Site_msg_required_Logo_extension {
            get {
                return ResourceManager.GetString("Site_msg_required_Logo_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do Logo do Site é obrigatório..
        /// </summary>
        public static string Site_msg_required_LogoNome {
            get {
                return ResourceManager.GetString("Site_msg_required_LogoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CNPJ deve ter 14 caracteres..
        /// </summary>
        public static string Site_msg_required_maxlength_Cnpj {
            get {
                return ResourceManager.GetString("Site_msg_required_maxlength_Cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Frase deve ter no máximo 60 caracteres..
        /// </summary>
        public static string Site_msg_required_maxlength_Frase {
            get {
                return ResourceManager.GetString("Site_msg_required_maxlength_Frase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome Fantasia deve ter no máximo 60 caracteres..
        /// </summary>
        public static string Site_msg_required_maxlength_Nome {
            get {
                return ResourceManager.GetString("Site_msg_required_maxlength_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Observações deve ter no máximo 60 caracteres..
        /// </summary>
        public static string Site_msg_required_maxlength_Observacoes {
            get {
                return ResourceManager.GetString("Site_msg_required_maxlength_Observacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Razão Social deve ter no máximo 60 caracteres..
        /// </summary>
        public static string Site_msg_required_maxlength_Razao_Social {
            get {
                return ResourceManager.GetString("Site_msg_required_maxlength_Razao_Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome Fantasia é obrigatório..
        /// </summary>
        public static string Site_msg_required_Nome {
            get {
                return ResourceManager.GetString("Site_msg_required_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Logo é obrigatório..
        /// </summary>
        public static string Site_msg_required_NomeLogo {
            get {
                return ResourceManager.GetString("Site_msg_required_NomeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Observações é obrigatório..
        /// </summary>
        public static string Site_msg_required_Observacoes {
            get {
                return ResourceManager.GetString("Site_msg_required_Observacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Razão Social é obrigatório..
        /// </summary>
        public static string Site_msg_required_Razao_Social {
            get {
                return ResourceManager.GetString("Site_msg_required_Razao_Social", resourceCulture);
            }
        }
    }
}
