//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Modulo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceModulo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceModulo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Modulo.ResourceModulo", typeof(ResourceModulo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulos.
        /// </summary>
        public static string Modulo_lbl_Modulo {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação Corretiva.
        /// </summary>
        public static string Modulo_lbl_Modulo_acao_corretiva {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_acao_corretiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrativo.
        /// </summary>
        public static string Modulo_lbl_Modulo_administrativo {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_administrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise Crítica do SG.
        /// </summary>
        public static string Modulo_lbl_Modulo_analise_critica {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_analise_critica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoria.
        /// </summary>
        public static string Modulo_lbl_Modulo_auditoria {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_auditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control-Doc.
        /// </summary>
        public static string Modulo_lbl_Modulo_controldoc {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_controldoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Melhoria.
        /// </summary>
        public static string Modulo_lbl_Modulo_gestao_melhoria {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_gestao_melhoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Risco.
        /// </summary>
        public static string Modulo_lbl_Modulo_gestao_risco {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_gestao_risco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicadores.
        /// </summary>
        public static string Modulo_lbl_Modulo_indicadores {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_indicadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumentos.
        /// </summary>
        public static string Modulo_lbl_Modulo_intrumentos {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_intrumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenças.
        /// </summary>
        public static string Modulo_lbl_Modulo_licencas {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_licencas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Conformidade.
        /// </summary>
        public static string Modulo_lbl_Modulo_nao_conformidade {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_nao_conformidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualificacao de Fornecedores.
        /// </summary>
        public static string Modulo_lbl_Modulo_qualificacao_fornecedores {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_qualificacao_fornecedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos Humanos.
        /// </summary>
        public static string Modulo_lbl_Modulo_RH {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_RH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Aprovação.
        /// </summary>
        public static string Modulo_lbl_Modulo_workflow {
            get {
                return ResourceManager.GetString("Modulo_lbl_Modulo_workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulos que Acessa.
        /// </summary>
        public static string Modulo_lbl_titulo {
            get {
                return ResourceManager.GetString("Modulo_lbl_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione pelo menos um módulo de acesso..
        /// </summary>
        public static string Modulo_msg_required_minlength {
            get {
                return ResourceManager.GetString("Modulo_msg_required_minlength", resourceCulture);
            }
        }
    }
}
