//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Cargo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceCargo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCargo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Cargo.ResourceCargo", typeof(ResourceCargo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string Cargo_lbl_Cargo {
            get {
                return ResourceManager.GetString("Cargo_lbl_Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargos.
        /// </summary>
        public static string Cargo_lbl_Cargos {
            get {
                return ResourceManager.GetString("Cargo_lbl_Cargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha os Cargos para o site.
        /// </summary>
        public static string Cargo_lbl_Escolha_cargo {
            get {
                return ResourceManager.GetString("Cargo_lbl_Escolha_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo excluido com sucesso..
        /// </summary>
        public static string Cargo_msg_exluir {
            get {
                return ResourceManager.GetString("Cargo_msg_exluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Ativar o cargo?.
        /// </summary>
        public static string Cargo_msg_icone_ativo_ativar {
            get {
                return ResourceManager.GetString("Cargo_msg_icone_ativo_ativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Inativar o cargo?.
        /// </summary>
        public static string Cargo_msg_icone_ativo_inativar {
            get {
                return ResourceManager.GetString("Cargo_msg_icone_ativo_inativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status modificado com sucesso..
        /// </summary>
        public static string Cargo_msg_icone_ativo_valid {
            get {
                return ResourceManager.GetString("Cargo_msg_icone_ativo_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Excluir o cargo?.
        /// </summary>
        public static string Cargo_msg_icone_excluir {
            get {
                return ResourceManager.GetString("Cargo_msg_icone_excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo salvo com sucesso..
        /// </summary>
        public static string Cargo_msg_salva_valid {
            get {
                return ResourceManager.GetString("Cargo_msg_salva_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionalidades.
        /// </summary>
        public static string Cargo_Titulo_Funcionalidade {
            get {
                return ResourceManager.GetString("Cargo_Titulo_Funcionalidade", resourceCulture);
            }
        }
    }
}
