//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Auditoria {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceAuditoria {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceAuditoria() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Auditoria.ResourceAuditoria", typeof(ResourceAuditoria).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normas.
        /// </summary>
        public static string Auditoria_btn_Normas {
            get {
                return ResourceManager.GetString("Auditoria_btn_Normas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string Auditoria_lbl_anterior {
            get {
                return ResourceManager.GetString("Auditoria_lbl_anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestor.
        /// </summary>
        public static string Auditoria_lbl_Gestor {
            get {
                return ResourceManager.GetString("Auditoria_lbl_Gestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximo.
        /// </summary>
        public static string Auditoria_lbl_proximo {
            get {
                return ResourceManager.GetString("Auditoria_lbl_proximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programa de Auditoria Interna.
        /// </summary>
        public static string Auditoria_lbl_titulo {
            get {
                return ResourceManager.GetString("Auditoria_lbl_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerentes.
        /// </summary>
        public static string Auditoria_lbl_titulo_Gerentes {
            get {
                return ResourceManager.GetString("Auditoria_lbl_titulo_Gerentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo / Departamento.
        /// </summary>
        public static string Auditoria_lbl_titulo_processo {
            get {
                return ResourceManager.GetString("Auditoria_lbl_titulo_processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Campo Gestor é obrigatório..
        /// </summary>
        public static string Auditoria_msg_required_Gestor {
            get {
                return ResourceManager.GetString("Auditoria_msg_required_Gestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano de Auditoria Interna (PLAI).
        /// </summary>
        public static string PlanoAuditoriaInterna {
            get {
                return ResourceManager.GetString("PlanoAuditoriaInterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro salvo com sucesso..
        /// </summary>
        public static string RegistroSalvoComSucesso {
            get {
                return ResourceManager.GetString("RegistroSalvoComSucesso", resourceCulture);
            }
        }
    }
}
