// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ControlDoc_Licencas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ControlDoc_Licencas));
        
        string IMigrationMetadata.Id
        {
            get { return "201712292113571_ControlDoc_Licencas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
