// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_colunas_indicadores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_colunas_indicadores));
        
        string IMigrationMetadata.Id
        {
            get { return "201712222107385_update_colunas_indicadores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
