// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tags_Produto_nao_obrigatoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tags_Produto_nao_obrigatoria));
        
        string IMigrationMetadata.Id
        {
            get { return "201712211756148_tags_Produto_nao_obrigatoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
