// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alteraçãomapeamentoRegistroConformidade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteraçãomapeamentoRegistroConformidade));
        
        string IMigrationMetadata.Id
        {
            get { return "201709182026166_alteração-mapeamento-Registro-Conformidade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
