// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class REtirado_Relacionamento_Usuario_de_AnaliseCriticaTema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(REtirado_Relacionamento_Usuario_de_AnaliseCriticaTema));
        
        string IMigrationMetadata.Id
        {
            get { return "201709121720017_REtirado_Relacionamento_Usuario_de_AnaliseCriticaTema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
