// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adicao_Relacionamento_USuario_Com_AnaliseCritica : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adicao_Relacionamento_USuario_Com_AnaliseCritica));
        
        string IMigrationMetadata.Id
        {
            get { return "201709121640065_Adicao_Relacionamento_USuario_Com_AnaliseCritica"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
