// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ControlDoc_Registros_Rotinas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ControlDoc_Registros_Rotinas));
        
        string IMigrationMetadata.Id
        {
            get { return "201712300149328_ControlDoc_Registros_Rotinas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
