// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adicaocampoAprovacaoRegistroAcaoImediata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicaocampoAprovacaoRegistroAcaoImediata));
        
        string IMigrationMetadata.Id
        {
            get { return "201709191357023_adicao-campo-Aprovacao-RegistroAcaoImediata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
