// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alteracao_Indicadores1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alteracao_Indicadores1));
        
        string IMigrationMetadata.Id
        {
            get { return "201709251410238_Alteracao_Indicadores1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
