// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alter_table_Avaliacao_Criticiada_Resultado_Incerteza_Erro_Pata_String : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_table_Avaliacao_Criticiada_Resultado_Incerteza_Erro_Pata_String));
        
        string IMigrationMetadata.Id
        {
            get { return "201712101518087_alter_table_Avaliacao_Criticiada_Resultado_Incerteza_Erro_Pata_String"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
