//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.ControlDoc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceControlDoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceControlDoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.ControlDoc.ResourceControlDoc", typeof(ResourceControlDoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovador.
        /// </summary>
        public static string ControlDoc_lbl_Aprovador {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Aprovador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovadores.
        /// </summary>
        public static string ControlDoc_lbl_Aprovadores {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Aprovadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo.
        /// </summary>
        public static string ControlDoc_lbl_Arquivo {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Arquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro.
        /// </summary>
        public static string ControlDoc_lbl_Cadastro {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Cadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string ControlDoc_lbl_Categoria {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causa.
        /// </summary>
        public static string ControlDoc_lbl_Causa {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Causa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Emissão.
        /// </summary>
        public static string ControlDoc_lbl_DataEmissao {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_DataEmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Notificação.
        /// </summary>
        public static string ControlDoc_lbl_DataNotificacao {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_DataNotificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Vencimento.
        /// </summary>
        public static string ControlDoc_lbl_DataVencimento {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_DataVencimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string ControlDoc_lbl_DocsExternos {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_DocsExternos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento necessita de revisão periódica?.
        /// </summary>
        public static string ControlDoc_lbl_DocumentoNecessitaRevisaoPeriodica {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_DocumentoNecessitaRevisaoPeriodica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elaborador.
        /// </summary>
        public static string ControlDoc_lbl_Elaborador {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Elaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato.
        /// </summary>
        public static string ControlDoc_lbl_Escolha {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Escolha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluxo.
        /// </summary>
        public static string ControlDoc_lbl_Fluxo {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Fluxo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Risco.
        /// </summary>
        public static string ControlDoc_lbl_GestaoRisco {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_GestaoRisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação do Risco.
        /// </summary>
        public static string ControlDoc_lbl_IdentificacaoRisco {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_IdentificacaoRisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa.
        /// </summary>
        public static string ControlDoc_lbl_Justificativa {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Justificativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licença.
        /// </summary>
        public static string ControlDoc_lbl_Licenca {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Licenca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link de acesso.
        /// </summary>
        public static string ControlDoc_lbl_LinkAcesso {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_LinkAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem:.
        /// </summary>
        public static string ControlDoc_lbl_Mensagem {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Mensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Fluxo.
        /// </summary>
        public static string ControlDoc_lbl_NovoFluxo {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_NovoFluxo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string ControlDoc_lbl_Numero {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Ação.
        /// </summary>
        public static string ControlDoc_lbl_NumeroAcao {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_NumeroAcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número do Documento.
        /// </summary>
        public static string ControlDoc_lbl_NumeroDocumento {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_NumeroDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string ControlDoc_lbl_Processo {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos.
        /// </summary>
        public static string ControlDoc_lbl_Recursos {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Recursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros.
        /// </summary>
        public static string ControlDoc_lbl_Registros {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Registros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        public static string ControlDoc_lbl_Responsavel_Risco {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Responsavel_Risco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisão.
        /// </summary>
        public static string ControlDoc_lbl_Revisao {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Revisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risco.
        /// </summary>
        public static string ControlDoc_lbl_Risco {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Risco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riscos.
        /// </summary>
        public static string ControlDoc_lbl_Riscos {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Riscos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotina.
        /// </summary>
        public static string ControlDoc_lbl_Rotina {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Rotina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar Todos.
        /// </summary>
        public static string ControlDoc_lbl_SelecionarTodos {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_SelecionarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla.
        /// </summary>
        public static string ControlDoc_lbl_Sigla {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Sigla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto.
        /// </summary>
        public static string ControlDoc_lbl_Texto {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título do Documento.
        /// </summary>
        public static string ControlDoc_lbl_TituloDocumento {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_TituloDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string ControlDoc_lbl_Upload {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizar Workflow?.
        /// </summary>
        public static string ControlDoc_lbl_UtilizarWorkflow {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_UtilizarWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificador.
        /// </summary>
        public static string ControlDoc_lbl_Verificador {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Verificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificadores.
        /// </summary>
        public static string ControlDoc_lbl_Verificadores {
            get {
                return ResourceManager.GetString("ControlDoc_lbl_Verificadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O documento &quot;{0}&quot; que tentou abir está em revisão por outro usuário..
        /// </summary>
        public static string ControlDoc_msg_documentoEmUso {
            get {
                return ResourceManager.GetString("ControlDoc_msg_documentoEmUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É preciso selecionar um Aprovador..
        /// </summary>
        public static string ControlDoc_msg_erro_required_Aprovadores {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_Aprovadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É preciso que seja selecionado ao menos 1 template para o documento..
        /// </summary>
        public static string ControlDoc_msg_erro_required_DocTemplate {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_DocTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade &quot;Data da alteração&quot; é obrigatório..
        /// </summary>
        public static string ControlDoc_msg_erro_required_DtAlteracao {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_DtAlteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;Data da Notificação&quot; é obrigatório..
        /// </summary>
        public static string ControlDoc_msg_erro_required_DtNotificacao {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_DtNotificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;Tem para revisão periódica?&quot; é obrigatório..
        /// </summary>
        public static string ControlDoc_msg_erro_required_FlRevisaoPeriodica {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_FlRevisaoPeriodica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade &quot;Status&quot; é obrigatório..
        /// </summary>
        public static string ControlDoc_msg_erro_required_FlStatus {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_FlStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;Tem para workflow?&quot; é obrigatório..
        /// </summary>
        public static string ControlDoc_msg_erro_required_FlWorkFlow {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_FlWorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;Categoria&quot; é obrigatório..
        /// </summary>
        public static string ControlDoc_msg_erro_required_IdCategoria {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_IdCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;Identificador Documento&quot; é obrigatório..
        /// </summary>
        public static string ControlDoc_msg_erro_required_IdDocIdentificador {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_IdDocIdentificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;Código do elaborador&quot; é obrigatório..
        /// </summary>
        public static string ControlDoc_msg_erro_required_IdElaborador {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_IdElaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Campo &quot;Sigla&quot; é obrigatorio..
        /// </summary>
        public static string ControlDoc_msg_erro_required_IdSigla {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_IdSigla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;Site&quot; é obrigatório..
        /// </summary>
        public static string ControlDoc_msg_erro_required_IdSite {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_IdSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade &quot;Usuario Inclusor&quot; é obrigatória..
        /// </summary>
        public static string ControlDoc_msg_erro_required_IdUsuarioIncluiu {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_IdUsuarioIncluiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;Número Documento&quot; é obrigatório..
        /// </summary>
        public static string ControlDoc_msg_erro_required_NumeroDocumento {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_NumeroDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;Título&quot; é obrigatório..
        /// </summary>
        public static string ControlDoc_msg_erro_required_Titulo {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É preciso selecionar um Verificador..
        /// </summary>
        public static string ControlDoc_msg_erro_required_Verificadores {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_required_Verificadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este documento já está em revisão..
        /// </summary>
        public static string ControlDoc_msg_erro_Revisao_Existente {
            get {
                return ResourceManager.GetString("ControlDoc_msg_erro_Revisao_Existente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento sem revisão..
        /// </summary>
        public static string ControlDoc_msg_SemRevisao {
            get {
                return ResourceManager.GetString("ControlDoc_msg_SemRevisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento salvo com sucesso..
        /// </summary>
        public static string ControlDoc_msg_Success {
            get {
                return ResourceManager.GetString("ControlDoc_msg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento enviado para Aprovação..
        /// </summary>
        public static string ControlDoc_msg_Success_Aprovacao {
            get {
                return ResourceManager.GetString("ControlDoc_msg_Success_Aprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento enviado para Aprovação, porém ocorreu falha no envio da notificação..
        /// </summary>
        public static string ControlDoc_msg_Success_Aprovacao_Falha_Email {
            get {
                return ResourceManager.GetString("ControlDoc_msg_Success_Aprovacao_Falha_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Aprovado com sucesso..
        /// </summary>
        public static string ControlDoc_msg_Success_Aprovado {
            get {
                return ResourceManager.GetString("ControlDoc_msg_Success_Aprovado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento enviado para Elaboração..
        /// </summary>
        public static string ControlDoc_msg_Success_Eleboracao {
            get {
                return ResourceManager.GetString("ControlDoc_msg_Success_Eleboracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento enviado para Elaboração, porém ocorreu falha no envio da notificação..
        /// </summary>
        public static string ControlDoc_msg_Success_Eleboracao_Falha_Email {
            get {
                return ResourceManager.GetString("ControlDoc_msg_Success_Eleboracao_Falha_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento enviado para Verificação..
        /// </summary>
        public static string ControlDoc_msg_Success_Verificacao {
            get {
                return ResourceManager.GetString("ControlDoc_msg_Success_Verificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento enviado para Verificação, porém ocorreu falha no envio da notificação..
        /// </summary>
        public static string ControlDoc_msg_Success_Verificacao_Falha_Email {
            get {
                return ResourceManager.GetString("ControlDoc_msg_Success_Verificacao_Falha_Email", resourceCulture);
            }
        }
    }
}
