//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Login {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLogin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Login.ResourceLogin", typeof(ResourceLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Atual.
        /// </summary>
        public static string AlterarSenha_lbl_placeholder_Senha_atual {
            get {
                return ResourceManager.GetString("AlterarSenha_lbl_placeholder_Senha_atual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme a nova Senha.
        /// </summary>
        public static string AlterarSenha_lbl_placeholder_Senha_confirma {
            get {
                return ResourceManager.GetString("AlterarSenha_lbl_placeholder_Senha_confirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Senha.
        /// </summary>
        public static string AlterarSenha_lbl_placeholder_Senha_nova {
            get {
                return ResourceManager.GetString("AlterarSenha_lbl_placeholder_Senha_nova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique sua caixa de e-mail para alteração de senha..
        /// </summary>
        public static string AlterarSenha_msg_erro_token_ativo {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_erro_token_ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Senha Atual é obrigatório..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_atual {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_atual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Confirmar Senha é obrigatório..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_confirma {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_confirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nova Senha deve ser igual ao Confirmar Senha..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_confirma_equals {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_confirma_equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Confirma Senha deve ter no mínimo 6 caracteres..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_confirma_minlength {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_confirma_minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Nova Senha não pode ser igual a Atual..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_notequals {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_notequals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nova Senha é obrigatório..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_nova {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_nova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nova Senha deve ter no mínimo 6 caracteres..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_nova_minlength {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_nova_minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha deve ser forte ou muito forte..
        /// </summary>
        public static string AlterarSenha_msg_required_Senha_nova_strong_pwd {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_required_Senha_nova_strong_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha Atual não confere..
        /// </summary>
        public static string AlterarSenha_msg_Senha_error_equals {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_Senha_error_equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração de Senha efetuada com sucesso..
        /// </summary>
        public static string AlterarSenha_msg_Senha_valid_change {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_Senha_valid_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario inválido.
        /// </summary>
        public static string AlterarSenha_msg_Usuario_invalid {
            get {
                return ResourceManager.GetString("AlterarSenha_msg_Usuario_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Senha.
        /// </summary>
        public static string AlterarSenha_titulo {
            get {
                return ResourceManager.GetString("AlterarSenha_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Login_lbl_placeholder_Email {
            get {
                return ResourceManager.GetString("Login_lbl_placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Login_lbl_placeholder_Senha {
            get {
                return ResourceManager.GetString("Login_lbl_placeholder_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário bloqueado por excesso de tentativas..
        /// </summary>
        public static string Login_msg_Bloqueado {
            get {
                return ResourceManager.GetString("Login_msg_Bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email não encontrado no sistema..
        /// </summary>
        public static string Login_msg_Email_not_found {
            get {
                return ResourceManager.GetString("Login_msg_Email_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há um problema com os dados cadastrais da sua empresa, entre em contato com o suporte da Isotec..
        /// </summary>
        public static string Login_msg_invalid_login {
            get {
                return ResourceManager.GetString("Login_msg_invalid_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválido..
        /// </summary>
        public static string Login_msg_Login_or_Senha_invalid {
            get {
                return ResourceManager.GetString("Login_msg_Login_or_Senha_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Email é obrigatório..
        /// </summary>
        public static string Login_msg_required_Email {
            get {
                return ResourceManager.GetString("Login_msg_required_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato de e-mail não é válido..
        /// </summary>
        public static string Login_msg_required_email_error_format {
            get {
                return ResourceManager.GetString("Login_msg_required_email_error_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário a seleção do Captcha..
        /// </summary>
        public static string Login_msg_required_Recaptcha {
            get {
                return ResourceManager.GetString("Login_msg_required_Recaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Senha é obrigatório..
        /// </summary>
        public static string Login_msg_required_Senha {
            get {
                return ResourceManager.GetString("Login_msg_required_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário deve estar ativo..
        /// </summary>
        public static string Login_msg_UsuarioDeveEstarAtivo {
            get {
                return ResourceManager.GetString("Login_msg_UsuarioDeveEstarAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário expirado..
        /// </summary>
        public static string Login_msg_UsuarioExpirado {
            get {
                return ResourceManager.GetString("Login_msg_UsuarioExpirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_titulo {
            get {
                return ResourceManager.GetString("Login_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso o E-mail esteja cadastrado no sistema, você receberá um e-mail com a nova senha..
        /// </summary>
        public static string RecuperarSenha_msg_Email_not_found {
            get {
                return ResourceManager.GetString("RecuperarSenha_msg_Email_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso o E-mail esteja cadastrado no sistema, você receberá um e-mail com a nova senha..
        /// </summary>
        public static string RecuperaSenha_msg_Email_valid_recovery {
            get {
                return ResourceManager.GetString("RecuperaSenha_msg_Email_valid_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao recuperar a senha. Entre em contato com o administrador..
        /// </summary>
        public static string RecuperaSenha_msg_invalid_recovery {
            get {
                return ResourceManager.GetString("RecuperaSenha_msg_invalid_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacte o Admintrador para realizar operação..
        /// </summary>
        public static string RecuperaSenha_msg_Usuario_Compartilhado {
            get {
                return ResourceManager.GetString("RecuperaSenha_msg_Usuario_Compartilhado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recupere Sua Senha.
        /// </summary>
        public static string RecuperaSenha_titulo {
            get {
                return ResourceManager.GetString("RecuperaSenha_titulo", resourceCulture);
            }
        }
    }
}
