//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceNotificacaoMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNotificacaoMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.ResourceNotificacaoMensagem", typeof(ResourceNotificacaoMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro salvo, porem não foi possivel notificar o responsavl pela próxima etapa..
        /// </summary>
        public static string ErroAoNotificarResponsavelPelaProximaEtapa {
            get {
                return ResourceManager.GetString("ErroAoNotificarResponsavelPelaProximaEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimiza.
        /// </summary>
        public static string Miniza {
            get {
                return ResourceManager.GetString("Miniza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificação de Ação Corretiva.
        /// </summary>
        public static string msgNotificacaoAcaoCorretiva {
            get {
                return ResourceManager.GetString("msgNotificacaoAcaoCorretiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificação de Controle de Documentos.
        /// </summary>
        public static string msgNotificacaoControlDoc {
            get {
                return ResourceManager.GetString("msgNotificacaoControlDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificação de Gestão de Risco.
        /// </summary>
        public static string MsgNotificacaoGestaoDeRiscos {
            get {
                return ResourceManager.GetString("MsgNotificacaoGestaoDeRiscos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificação de Não Conformidade.
        /// </summary>
        public static string MsgNotificacaoNaoConformidade {
            get {
                return ResourceManager.GetString("MsgNotificacaoNaoConformidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro .
        /// </summary>
        public static string MsgOcorreuErro {
            get {
                return ResourceManager.GetString("MsgOcorreuErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu arquivo não foi carregado .
        /// </summary>
        public static string MsgValidaArquivoNaoCarregado {
            get {
                return ResourceManager.GetString("MsgValidaArquivoNaoCarregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo de um arquivo é .
        /// </summary>
        public static string MsgValidaUploadArquivoUnico {
            get {
                return ResourceManager.GetString("MsgValidaUploadArquivoUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Qualit Não Conformidade.
        /// </summary>
        public static string NaoConformidade_msg_DsAssunto {
            get {
                return ResourceManager.GetString("NaoConformidade_msg_DsAssunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta mensagem será encaminhada através do e-mail suporte@equalit.com.br, à caixa de mensagem deste usuário selecionado e terá esta composição:
        ///Nome do cliente:{0}
        ///Você está recebendo uma notificação do sistema de gestão e-Qualit, existe uma não conformidade no sistema a qual necessita sua intervenção.
        ///Por favor, acesse seu sistema de gestão, no menu – Registros – módulo – Não Conformidade, vá ao registro número “{1}”.
        ///Acesse: www.equalit.com.br 
        ///Obrigado (a).
        ///Não responda a esta mensagem..
        /// </summary>
        public static string NaoConformidade_msg_DsMensagem {
            get {
                return ResourceManager.GetString("NaoConformidade_msg_DsMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro salvo com sucesso!.
        /// </summary>
        public static string RegistroSalvoComSucesso {
            get {
                return ResourceManager.GetString("RegistroSalvoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela Cheia.
        /// </summary>
        public static string TelaCheia {
            get {
                return ResourceManager.GetString("TelaCheia", resourceCulture);
            }
        }
    }
}
