//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Processo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceProcesso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceProcesso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Processo.ResourceProcesso", typeof(ResourceProcesso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atividade.
        /// </summary>
        public static string Processo_lbl_Atividade {
            get {
                return ResourceManager.GetString("Processo_lbl_Atividade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string Processo_lbl_Ativo {
            get {
                return ResourceManager.GetString("Processo_lbl_Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos Aplicáveis.
        /// </summary>
        public static string Processo_lbl_Docs_aplicaveis {
            get {
                return ResourceManager.GetString("Processo_lbl_Docs_aplicaveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Processo.
        /// </summary>
        public static string Processo_lbl_novo_processo {
            get {
                return ResourceManager.GetString("Processo_lbl_novo_processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atividade.
        /// </summary>
        public static string Processo_lbl_placeholder_Atividade {
            get {
                return ResourceManager.GetString("Processo_lbl_placeholder_Atividade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos Aplicáveis.
        /// </summary>
        public static string Processo_lbl_placeholder_Docs_aplicaveis {
            get {
                return ResourceManager.GetString("Processo_lbl_placeholder_Docs_aplicaveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o nome do Processo.
        /// </summary>
        public static string Processo_lbl_placeholder_Nome {
            get {
                return ResourceManager.GetString("Processo_lbl_placeholder_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processos.
        /// </summary>
        public static string Processo_lbl_placeholder_Processos {
            get {
                return ResourceManager.GetString("Processo_lbl_placeholder_Processos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisitos Aplicáveis.
        /// </summary>
        public static string Processo_lbl_placeholder_Requisitos_aplicaveis {
            get {
                return ResourceManager.GetString("Processo_lbl_placeholder_Requisitos_aplicaveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string Processo_lbl_Processo {
            get {
                return ResourceManager.GetString("Processo_lbl_Processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualidade.
        /// </summary>
        public static string Processo_lbl_Processo_value {
            get {
                return ResourceManager.GetString("Processo_lbl_Processo_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processos.
        /// </summary>
        public static string Processo_lbl_Processos {
            get {
                return ResourceManager.GetString("Processo_lbl_Processos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisitos Aplicáveis.
        /// </summary>
        public static string Processo_lbl_Requisitos_aplicaveis {
            get {
                return ResourceManager.GetString("Processo_lbl_Requisitos_aplicaveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processos.
        /// </summary>
        public static string Processo_lbl_titulo {
            get {
                return ResourceManager.GetString("Processo_lbl_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório a criação de um processo..
        /// </summary>
        public static string Processo_msg_min_lenght {
            get {
                return ResourceManager.GetString("Processo_msg_min_lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Id desse processo é obrigatório para atualiza-lo..
        /// </summary>
        public static string Processo_msg_required_IdProcesso {
            get {
                return ResourceManager.GetString("Processo_msg_required_IdProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Id do Site é obrigatório..
        /// </summary>
        public static string Processo_msg_required_IdSite {
            get {
                return ResourceManager.GetString("Processo_msg_required_IdSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Processo deve ter no máximo 60 caracteres..
        /// </summary>
        public static string Processo_msg_required_maxlength_Nome {
            get {
                return ResourceManager.GetString("Processo_msg_required_maxlength_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Processo deve ter no minimo 2 caracteres..
        /// </summary>
        public static string Processo_msg_required_minlength_Nome {
            get {
                return ResourceManager.GetString("Processo_msg_required_minlength_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Processo é obrigatório..
        /// </summary>
        public static string Processo_msg_required_Nome {
            get {
                return ResourceManager.GetString("Processo_msg_required_Nome", resourceCulture);
            }
        }
    }
}
