//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.AnaliseCritica {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceAnaliseCritica {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceAnaliseCritica() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.AnaliseCritica.ResourceAnaliseCritica", typeof(ResourceAnaliseCritica).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string AC_lbl_Acoes {
            get {
                return ResourceManager.GetString("AC_lbl_Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ata de Análise Crítica.
        /// </summary>
        public static string AC_lbl_Ata {
            get {
                return ResourceManager.GetString("AC_lbl_Ata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causa.
        /// </summary>
        public static string AC_lbl_causa {
            get {
                return ResourceManager.GetString("AC_lbl_causa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string AC_lbl_Descricao {
            get {
                return ResourceManager.GetString("AC_lbl_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Criação.
        /// </summary>
        public static string AC_lbl_DtCriacao {
            get {
                return ResourceManager.GetString("AC_lbl_DtCriacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função.
        /// </summary>
        public static string AC_lbl_Funcao {
            get {
                return ResourceManager.GetString("AC_lbl_Funcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Risco.
        /// </summary>
        public static string AC_lbl_Gestao_de_risco {
            get {
                return ResourceManager.GetString("AC_lbl_Gestao_de_risco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação do Risco.
        /// </summary>
        public static string AC_lbl_Identificacao_risco {
            get {
                return ResourceManager.GetString("AC_lbl_Identificacao_risco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string AC_lbl_Nome {
            get {
                return ResourceManager.GetString("AC_lbl_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Análise Crítica.
        /// </summary>
        public static string AC_lbl_nova_analise_critica {
            get {
                return ResourceManager.GetString("AC_lbl_nova_analise_critica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Participante.
        /// </summary>
        public static string AC_lbl_novo_participante {
            get {
                return ResourceManager.GetString("AC_lbl_novo_participante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string AC_lbl_Numero {
            get {
                return ResourceManager.GetString("AC_lbl_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número da Ata de Análise Crítica.
        /// </summary>
        public static string AC_lbl_placeholder_Ata {
            get {
                return ResourceManager.GetString("AC_lbl_placeholder_Ata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite uma descrição.
        /// </summary>
        public static string AC_lbl_placeholder_Descricao {
            get {
                return ResourceManager.GetString("AC_lbl_placeholder_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __/__/____.
        /// </summary>
        public static string AC_lbl_placeholder_DtCriacao {
            get {
                return ResourceManager.GetString("AC_lbl_placeholder_DtCriacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __/__/____.
        /// </summary>
        public static string AC_lbl_placeholder_DtProximaAnalise {
            get {
                return ResourceManager.GetString("AC_lbl_placeholder_DtProximaAnalise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha o Participante para saber a função.
        /// </summary>
        public static string AC_lbl_placeholder_Funcao {
            get {
                return ResourceManager.GetString("AC_lbl_placeholder_Funcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite uma identificação do risco..
        /// </summary>
        public static string AC_lbl_placeholder_Identificacao_risco {
            get {
                return ResourceManager.GetString("AC_lbl_placeholder_Identificacao_risco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data próxima Análise.
        /// </summary>
        public static string AC_lbl_Proxima_analise {
            get {
                return ResourceManager.GetString("AC_lbl_Proxima_analise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        public static string AC_lbl_Responsavel {
            get {
                return ResourceManager.GetString("AC_lbl_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável por análise e definição de ação.
        /// </summary>
        public static string AC_lbl_Responsavel_definicao {
            get {
                return ResourceManager.GetString("AC_lbl_Responsavel_definicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risco.
        /// </summary>
        public static string AC_lbl_Risco {
            get {
                return ResourceManager.GetString("AC_lbl_Risco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto.
        /// </summary>
        public static string AC_lbl_Risco_alto {
            get {
                return ResourceManager.GetString("AC_lbl_Risco_alto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leve.
        /// </summary>
        public static string AC_lbl_Risco_leve {
            get {
                return ResourceManager.GetString("AC_lbl_Risco_leve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Médio.
        /// </summary>
        public static string AC_lbl_Risco_medio {
            get {
                return ResourceManager.GetString("AC_lbl_Risco_medio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um tema.
        /// </summary>
        public static string AC_lbl_tema {
            get {
                return ResourceManager.GetString("AC_lbl_tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação da Análise Crítica.
        /// </summary>
        public static string AC_lbl_titulo_identificacao {
            get {
                return ResourceManager.GetString("AC_lbl_titulo_identificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temas.
        /// </summary>
        public static string AC_lbl_titulo_temas {
            get {
                return ResourceManager.GetString("AC_lbl_titulo_temas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise Crítica criada com sucesso..
        /// </summary>
        public static string AC_msg_criar_valid {
            get {
                return ResourceManager.GetString("AC_msg_criar_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Deletar esta Análise Crítica?.
        /// </summary>
        public static string AC_msg_icone_delete {
            get {
                return ResourceManager.GetString("AC_msg_icone_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Excluir esta Análise Crítica?.
        /// </summary>
        public static string AC_msg_icone_excluir {
            get {
                return ResourceManager.GetString("AC_msg_icone_excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Ata de Análise Crítica é obrigatório..
        /// </summary>
        public static string AC_msg_required_Ata {
            get {
                return ResourceManager.GetString("AC_msg_required_Ata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Possui Criticidade é obrigatório..
        /// </summary>
        public static string AC_msg_required_CriticidadeGestaoDeRisco {
            get {
                return ResourceManager.GetString("AC_msg_required_CriticidadeGestaoDeRisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Descrição é obrigatório..
        /// </summary>
        public static string AC_msg_required_Descricao {
            get {
                return ResourceManager.GetString("AC_msg_required_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Data de Criação é obrigatório..
        /// </summary>
        public static string AC_msg_required_DtCriacao {
            get {
                return ResourceManager.GetString("AC_msg_required_DtCriacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Data da Oróxima Análise é obrigatório..
        /// </summary>
        public static string AC_msg_required_DtProximaAnalise {
            get {
                return ResourceManager.GetString("AC_msg_required_DtProximaAnalise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Função é obrigatório..
        /// </summary>
        public static string AC_msg_required_Funcao {
            get {
                return ResourceManager.GetString("AC_msg_required_Funcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Identificação é obrigatório..
        /// </summary>
        public static string AC_msg_required_Identificacao_risco {
            get {
                return ResourceManager.GetString("AC_msg_required_Identificacao_risco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome do Participante é obrigatório..
        /// </summary>
        public static string AC_msg_required_Participante {
            get {
                return ResourceManager.GetString("AC_msg_required_Participante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Possui Gestão de Risco é obrigatório..
        /// </summary>
        public static string AC_msg_required_PossuiGestaoRisco {
            get {
                return ResourceManager.GetString("AC_msg_required_PossuiGestaoRisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Responsável é obrigatório..
        /// </summary>
        public static string AC_msg_required_Responsavel {
            get {
                return ResourceManager.GetString("AC_msg_required_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Responsável por Definição é obrigatório..
        /// </summary>
        public static string AC_msg_required_Responsavel_definicao {
            get {
                return ResourceManager.GetString("AC_msg_required_Responsavel_definicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha o Risco..
        /// </summary>
        public static string AC_msg_required_Risco {
            get {
                return ResourceManager.GetString("AC_msg_required_Risco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Temas é obrigatório..
        /// </summary>
        public static string AC_msg_required_Temas {
            get {
                return ResourceManager.GetString("AC_msg_required_Temas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise Crítica salva com sucesso..
        /// </summary>
        public static string AC_msg_save_valid {
            get {
                return ResourceManager.GetString("AC_msg_save_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa.
        /// </summary>
        public static string Justificativa {
            get {
                return ResourceManager.GetString("Justificativa", resourceCulture);
            }
        }
    }
}
