//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Fornecedores {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceFornecedores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFornecedores() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Fornecedores.ResourceFornecedores", typeof(ResourceFornecedores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controla Vencimento.
        /// </summary>
        public static string ControlaDataVencimento {
            get {
                return ResourceManager.GetString("ControlaDataVencimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor salvo com sucesso..
        /// </summary>
        public static string FornecedorSalvoComSucesso {
            get {
                return ResourceManager.GetString("FornecedorSalvoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Fornecedores.
        /// </summary>
        public static string Produto_btn_lbl_cadastro_fornecedor {
            get {
                return ResourceManager.GetString("Produto_btn_lbl_cadastro_fornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definição dos critérios para Avaliação.
        /// </summary>
        public static string Produto_btn_lbl_definiicao_criterio_avaliacao {
            get {
                return ResourceManager.GetString("Produto_btn_lbl_definiicao_criterio_avaliacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definição dos critérios para Qualificação.
        /// </summary>
        public static string Produto_btn_lbl_definiicao_criterio_qualificacao {
            get {
                return ResourceManager.GetString("Produto_btn_lbl_definiicao_criterio_qualificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Fornecedores.
        /// </summary>
        public static string Produto_btn_lbl_ver_fornecedor {
            get {
                return ResourceManager.GetString("Produto_btn_lbl_ver_fornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Produto_lbl_Acoes {
            get {
                return ResourceManager.GetString("Produto_lbl_Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especificação.
        /// </summary>
        public static string Produto_lbl_Especificacao {
            get {
                return ResourceManager.GetString("Produto_lbl_Especificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto/Serviço.
        /// </summary>
        public static string Produto_lbl_Nome {
            get {
                return ResourceManager.GetString("Produto_lbl_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Produto/Serviço.
        /// </summary>
        public static string Produto_lbl_NovoProduto {
            get {
                return ResourceManager.GetString("Produto_lbl_NovoProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite uma especificação.
        /// </summary>
        public static string Produto_lbl_placeholder_Especificacao {
            get {
                return ResourceManager.GetString("Produto_lbl_placeholder_Especificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Produto.
        /// </summary>
        public static string Produto_lbl_placeholder_Nome {
            get {
                return ResourceManager.GetString("Produto_lbl_placeholder_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Produto.
        /// </summary>
        public static string Produto_lbl_placeholder_Tags {
            get {
                return ResourceManager.GetString("Produto_lbl_placeholder_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        public static string Produto_lbl_Responsavel {
            get {
                return ResourceManager.GetString("Produto_lbl_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Produto_lbl_Status {
            get {
                return ResourceManager.GetString("Produto_lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Produto_lbl_Tags {
            get {
                return ResourceManager.GetString("Produto_lbl_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Site é obrigatório.
        /// </summary>
        public static string Produto_msg_erro_required_IdSite {
            get {
                return ResourceManager.GetString("Produto_msg_erro_required_IdSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especificação é obrigatória.
        /// </summary>
        public static string Produto_msg_required_Especificacao {
            get {
                return ResourceManager.GetString("Produto_msg_required_Especificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Produto/Serviço é obrigatório.
        /// </summary>
        public static string Produto_msg_required_Nome {
            get {
                return ResourceManager.GetString("Produto_msg_required_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Campo Responsavel é obrigatório.
        /// </summary>
        public static string Produto_msg_required_Responsavel {
            get {
                return ResourceManager.GetString("Produto_msg_required_Responsavel", resourceCulture);
            }
        }
    }
}
