//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.NaoConformidade {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceNaoConformidade {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNaoConformidade() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.NaoConformidade.ResourceNaoConformidade", typeof(ResourceNaoConformidade).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string NC_cabecalho_tabela_Numero {
            get {
                return ResourceManager.GetString("NC_cabecalho_tabela_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string NC_lbl_Acoes {
            get {
                return ResourceManager.GetString("NC_lbl_Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string NC_lbl_AI_Acao_descricao {
            get {
                return ResourceManager.GetString("NC_lbl_AI_Acao_descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação Imediata.
        /// </summary>
        public static string NC_lbl_AI_Acao_Imediata {
            get {
                return ResourceManager.GetString("NC_lbl_AI_Acao_Imediata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo de Evidência.
        /// </summary>
        public static string NC_lbl_AI_Arquivo_evidencia {
            get {
                return ResourceManager.GetString("NC_lbl_AI_Arquivo_evidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efetiva implementação.
        /// </summary>
        public static string NC_lbl_AI_Efetiva_implementacao {
            get {
                return ResourceManager.GetString("NC_lbl_AI_Efetiva_implementacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prazo implementação.
        /// </summary>
        public static string NC_lbl_AI_Prazo_implementacao {
            get {
                return ResourceManager.GetString("NC_lbl_AI_Prazo_implementacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável por implementar.
        /// </summary>
        public static string NC_lbl_AI_Responsavel_implementar {
            get {
                return ResourceManager.GetString("NC_lbl_AI_Responsavel_implementar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise da Causa.
        /// </summary>
        public static string NC_lbl_Analise_causa {
            get {
                return ResourceManager.GetString("NC_lbl_Analise_causa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo de Evidência.
        /// </summary>
        public static string NC_lbl_Arquivo_evidencia {
            get {
                return ResourceManager.GetString("NC_lbl_Arquivo_evidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do Registro.
        /// </summary>
        public static string NC_lbl_DsRegistro {
            get {
                return ResourceManager.GetString("NC_lbl_DsRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da descrição da ação:.
        /// </summary>
        public static string NC_lbl_DtDescricaoAcao {
            get {
                return ResourceManager.GetString("NC_lbl_DtDescricaoAcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Emissão.
        /// </summary>
        public static string NC_lbl_DtEmissao {
            get {
                return ResourceManager.GetString("NC_lbl_DtEmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Encerramento.
        /// </summary>
        public static string NC_lbl_DtEncerramento {
            get {
                return ResourceManager.GetString("NC_lbl_DtEncerramento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não conformidade de auditoria:.
        /// </summary>
        public static string NC_lbl_EAuditoria {
            get {
                return ResourceManager.GetString("NC_lbl_EAuditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação imediata é uma correção?.
        /// </summary>
        public static string NC_lbl_ECorrecao {
            get {
                return ResourceManager.GetString("NC_lbl_ECorrecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emissor.
        /// </summary>
        public static string NC_lbl_Emissor {
            get {
                return ResourceManager.GetString("NC_lbl_Emissor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Conformidade é procedente?.
        /// </summary>
        public static string NC_lbl_EProcedente {
            get {
                return ResourceManager.GetString("NC_lbl_EProcedente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi Eficaz.
        /// </summary>
        public static string NC_lbl_Foi_eficaz {
            get {
                return ResourceManager.GetString("NC_lbl_Foi_eficaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar gráfico.
        /// </summary>
        public static string NC_lbl_grafico {
            get {
                return ResourceManager.GetString("NC_lbl_grafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa.
        /// </summary>
        public static string NC_lbl_Justificativa {
            get {
                return ResourceManager.GetString("NC_lbl_Justificativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificativa / Controle.
        /// </summary>
        public static string NC_lbl_JustificativaControle {
            get {
                return ResourceManager.GetString("NC_lbl_JustificativaControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessita ação correção?.
        /// </summary>
        public static string NC_lbl_Necessita_AC {
            get {
                return ResourceManager.GetString("NC_lbl_Necessita_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Ação Corretiva:.
        /// </summary>
        public static string NC_lbl_Nm_acao_corretiva {
            get {
                return ResourceManager.GetString("NC_lbl_Nm_acao_corretiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string NC_lbl_NmRegistro {
            get {
                return ResourceManager.GetString("NC_lbl_NmRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Não Conformidade.
        /// </summary>
        public static string NC_lbl_nova_nao_conformidade {
            get {
                return ResourceManager.GetString("NC_lbl_nova_nao_conformidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parecer.
        /// </summary>
        public static string NC_lbl_Parecer {
            get {
                return ResourceManager.GetString("NC_lbl_Parecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string NC_lbl_placeholder_AI_Descricao {
            get {
                return ResourceManager.GetString("NC_lbl_placeholder_AI_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __/__/____.
        /// </summary>
        public static string NC_lbl_placeholder_AI_Efetiva_implementacao {
            get {
                return ResourceManager.GetString("NC_lbl_placeholder_AI_Efetiva_implementacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __/__/____.
        /// </summary>
        public static string NC_lbl_placeholder_AI_Prazo_implementacao {
            get {
                return ResourceManager.GetString("NC_lbl_placeholder_AI_Prazo_implementacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite uma descrição para a analise de causa.
        /// </summary>
        public static string NC_lbl_placeholder_Analise_causa {
            get {
                return ResourceManager.GetString("NC_lbl_placeholder_Analise_causa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escreva uma descrição para este registro.
        /// </summary>
        public static string NC_lbl_placeholder_Descricao_registro {
            get {
                return ResourceManager.GetString("NC_lbl_placeholder_Descricao_registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite uma descrição para o registro.
        /// </summary>
        public static string NC_lbl_placeholder_DsRegistro {
            get {
                return ResourceManager.GetString("NC_lbl_placeholder_DsRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __/__/____.
        /// </summary>
        public static string NC_lbl_placeholder_DtEmissao {
            get {
                return ResourceManager.GetString("NC_lbl_placeholder_DtEmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite uma justificativa.
        /// </summary>
        public static string NC_lbl_placeholder_Justificativa {
            get {
                return ResourceManager.GetString("NC_lbl_placeholder_Justificativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero do Registro.
        /// </summary>
        public static string NC_lbl_placeholder_NmRegistro {
            get {
                return ResourceManager.GetString("NC_lbl_placeholder_NmRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite uma descrição para o parecer..
        /// </summary>
        public static string NC_lbl_placeholder_Parecer {
            get {
                return ResourceManager.GetString("NC_lbl_placeholder_Parecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escreva algumas Tags.
        /// </summary>
        public static string NC_lbl_placeholder_Tags {
            get {
                return ResourceManager.GetString("NC_lbl_placeholder_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string NC_lbl_Processo {
            get {
                return ResourceManager.GetString("NC_lbl_Processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável por análise e definição de ação imediata:.
        /// </summary>
        public static string NC_lbl_Responsavel_definir_AC {
            get {
                return ResourceManager.GetString("NC_lbl_Responsavel_definir_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsavel por reverificação.
        /// </summary>
        public static string NC_lbl_Responsavel_reverificacao {
            get {
                return ResourceManager.GetString("NC_lbl_Responsavel_reverificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsavel por iniciar a tratativa da ação corretiva.
        /// </summary>
        public static string NC_lbl_Responsavel_tratativa {
            get {
                return ResourceManager.GetString("NC_lbl_Responsavel_tratativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsavel por Implementar.
        /// </summary>
        public static string NC_lbl_ResponsavelImplementar {
            get {
                return ResourceManager.GetString("NC_lbl_ResponsavelImplementar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação Imediata.
        /// </summary>
        public static string NC_lbl_Status_Acao_imediata {
            get {
                return ResourceManager.GetString("NC_lbl_Status_Acao_imediata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encerrada.
        /// </summary>
        public static string NC_lbl_Status_Encerrada {
            get {
                return ResourceManager.GetString("NC_lbl_Status_Encerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementação.
        /// </summary>
        public static string NC_lbl_Status_Implementacao {
            get {
                return ResourceManager.GetString("NC_lbl_Status_Implementacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverificação.
        /// </summary>
        public static string NC_lbl_Status_Reverificacao {
            get {
                return ResourceManager.GetString("NC_lbl_Status_Reverificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string NC_lbl_StatusEtapa {
            get {
                return ResourceManager.GetString("NC_lbl_StatusEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string NC_lbl_Tags {
            get {
                return ResourceManager.GetString("NC_lbl_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de não conformidade:.
        /// </summary>
        public static string NC_lbl_Tipo {
            get {
                return ResourceManager.GetString("NC_lbl_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Gráfico.
        /// </summary>
        public static string NC_lbl_tipo_grafico {
            get {
                return ResourceManager.GetString("NC_lbl_tipo_grafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação da Não Conformidade.
        /// </summary>
        public static string NC_lbl_titulo_identificacao {
            get {
                return ResourceManager.GetString("NC_lbl_titulo_identificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Conformidade criada com sucesso..
        /// </summary>
        public static string NC_msg_criar_valid {
            get {
                return ResourceManager.GetString("NC_msg_criar_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Conformidade excluida com sucesso..
        /// </summary>
        public static string NC_msg_delete_valid {
            get {
                return ResourceManager.GetString("NC_msg_delete_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo prazo implementação é obrigatório..
        /// </summary>
        public static string NC_msg_DtrPrazoImplementacao_required {
            get {
                return ResourceManager.GetString("NC_msg_DtrPrazoImplementacao_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Deletar esta Não Conformidade?.
        /// </summary>
        public static string NC_msg_icone_delete {
            get {
                return ResourceManager.GetString("NC_msg_icone_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Excluir esta Não Conformidade?.
        /// </summary>
        public static string NC_msg_icone_excluir {
            get {
                return ResourceManager.GetString("NC_msg_icone_excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Arquivo de Evidência é obrigatório..
        /// </summary>
        public static string NC_msg_required_AI_Arquivo_evidencia {
            get {
                return ResourceManager.GetString("NC_msg_required_AI_Arquivo_evidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Descrição é obrigatório..
        /// </summary>
        public static string NC_msg_required_AI_Descricao {
            get {
                return ResourceManager.GetString("NC_msg_required_AI_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Efetiva implementação é obrigatório..
        /// </summary>
        public static string NC_msg_required_AI_Efetiva_implementacao {
            get {
                return ResourceManager.GetString("NC_msg_required_AI_Efetiva_implementacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo 	Prazo implementação é obrigatório..
        /// </summary>
        public static string NC_msg_required_AI_Prazo_implementacao {
            get {
                return ResourceManager.GetString("NC_msg_required_AI_Prazo_implementacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Responsável por implementar é obrigatório..
        /// </summary>
        public static string NC_msg_required_AI_Responsavel_implementar {
            get {
                return ResourceManager.GetString("NC_msg_required_AI_Responsavel_implementar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Análise da Causa é obrigatório..
        /// </summary>
        public static string NC_msg_required_Analise_causa {
            get {
                return ResourceManager.GetString("NC_msg_required_Analise_causa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Descrição do Registro é obrigatório..
        /// </summary>
        public static string NC_msg_required_DsRegistro {
            get {
                return ResourceManager.GetString("NC_msg_required_DsRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Data da descrição da ação é obrigatório..
        /// </summary>
        public static string NC_msg_required_DtDescricao {
            get {
                return ResourceManager.GetString("NC_msg_required_DtDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Data Expiração é obrigatório..
        /// </summary>
        public static string NC_msg_required_DtEmissao {
            get {
                return ResourceManager.GetString("NC_msg_required_DtEmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo É Auditoria é obrigatório..
        /// </summary>
        public static string NC_msg_required_EAuditoria {
            get {
                return ResourceManager.GetString("NC_msg_required_EAuditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Ação imediata é uma correção? é obrigatório..
        /// </summary>
        public static string NC_msg_required_ECorrecao {
            get {
                return ResourceManager.GetString("NC_msg_required_ECorrecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Emissor é obrigatório..
        /// </summary>
        public static string NC_msg_required_Emissor {
            get {
                return ResourceManager.GetString("NC_msg_required_Emissor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Não Conformidade é procedente é obrigatório..
        /// </summary>
        public static string NC_msg_required_EProcedente {
            get {
                return ResourceManager.GetString("NC_msg_required_EProcedente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Foi Eficaz ? é obrigatório..
        /// </summary>
        public static string NC_msg_required_Foi_eficaz {
            get {
                return ResourceManager.GetString("NC_msg_required_Foi_eficaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Justificativa é obrigatório..
        /// </summary>
        public static string NC_msg_required_Justificativa {
            get {
                return ResourceManager.GetString("NC_msg_required_Justificativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Tipo é obrigatório..
        /// </summary>
        public static string NC_msg_required_minlength_DsRegistro {
            get {
                return ResourceManager.GetString("NC_msg_required_minlength_DsRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo URL deve ter no mínimo 4 caracteres..
        /// </summary>
        public static string NC_msg_required_minlength_Justificativa {
            get {
                return ResourceManager.GetString("NC_msg_required_minlength_Justificativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo descrição deve ter no mínimo 4 caracteres e no maximo 2000 caracteres..
        /// </summary>
        public static string NC_msg_required_minlength_max_descricao {
            get {
                return ResourceManager.GetString("NC_msg_required_minlength_max_descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Necessita ação correção? é obrigatório..
        /// </summary>
        public static string NC_msg_required_Necessita_AC {
            get {
                return ResourceManager.GetString("NC_msg_required_Necessita_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Necessita ação? é obrigatório..
        /// </summary>
        public static string NC_msg_required_NecessitaAcao {
            get {
                return ResourceManager.GetString("NC_msg_required_NecessitaAcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Processo é obrigatório..
        /// </summary>
        public static string NC_msg_required_Processo {
            get {
                return ResourceManager.GetString("NC_msg_required_Processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Responsável por análise e definição de ação imediata é obrigatório..
        /// </summary>
        public static string NC_msg_required_Responsavel_definir_AC {
            get {
                return ResourceManager.GetString("NC_msg_required_Responsavel_definir_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Responsavel por reverificação é obrigatório..
        /// </summary>
        public static string NC_msg_required_Responsavel_reverificacao {
            get {
                return ResourceManager.GetString("NC_msg_required_Responsavel_reverificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Responsavel por iniciar a tratativa é obrigatório..
        /// </summary>
        public static string NC_msg_required_Responsavel_tratativa {
            get {
                return ResourceManager.GetString("NC_msg_required_Responsavel_tratativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Tags é obrigatório..
        /// </summary>
        public static string NC_msg_required_Tags {
            get {
                return ResourceManager.GetString("NC_msg_required_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Tipo é obrigatório..
        /// </summary>
        public static string NC_msg_required_Tipo {
            get {
                return ResourceManager.GetString("NC_msg_required_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Conformidade salva com sucesso..
        /// </summary>
        public static string NC_msg_save_valid {
            get {
                return ResourceManager.GetString("NC_msg_save_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O data de descrição deve ser maior ou igual a data de emissão..
        /// </summary>
        public static string NC_msg_save_valid_DtDescricao {
            get {
                return ResourceManager.GetString("NC_msg_save_valid_DtDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A efetiva implementação deve ser maior ou igual a data de emissão..
        /// </summary>
        public static string NC_msg_save_valid_DtEvetivaImplementacao {
            get {
                return ResourceManager.GetString("NC_msg_save_valid_DtEvetivaImplementacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O prazo para implementação deve ser maior ou igual a data de emissão..
        /// </summary>
        public static string NC_msg_save_valid_DtPrazoImplementacao {
            get {
                return ResourceManager.GetString("NC_msg_save_valid_DtPrazoImplementacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A efetiva implementação deve ser menor ou igual a data atual..
        /// </summary>
        public static string NC_msg_save_valid_DtPrazoImpleNC_msg_save_valid_DtEvetivaImplementacaoAtual {
            get {
                return ResourceManager.GetString("NC_msg_save_valid_DtPrazoImpleNC_msg_save_valid_DtEvetivaImplementacaoAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A efetiva implementação deve ser maior ou igual a data de descrição..
        /// </summary>
        public static string NC_msg_save_valid_DtPrazoImpleNC_msg_save_valid_DtEvetivaImplementacaoDtDescricao {
            get {
                return ResourceManager.GetString("NC_msg_save_valid_DtPrazoImpleNC_msg_save_valid_DtEvetivaImplementacaoDtDescricao" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável por Análise e definição da ação.
        /// </summary>
        public static string ResponsavelPorDefinirAcao {
            get {
                return ResourceManager.GetString("ResponsavelPorDefinirAcao", resourceCulture);
            }
        }
    }
}
