//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Cliente {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceCliente {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCliente() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Cliente.ResourceCliente", typeof(ResourceCliente).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Cliente_lbl_Acao {
            get {
                return ResourceManager.GetString("Cliente_lbl_Acao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string Cliente_lbl_Acao_ativo {
            get {
                return ResourceManager.GetString("Cliente_lbl_Acao_ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa Captcha.
        /// </summary>
        public static string Cliente_lbl_Acao_captcha {
            get {
                return ResourceManager.GetString("Cliente_lbl_Acao_captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exige Senha Forte.
        /// </summary>
        public static string Cliente_lbl_Acao_senha_forte {
            get {
                return ResourceManager.GetString("Cliente_lbl_Acao_senha_forte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armazenar senhas utilizadas.
        /// </summary>
        public static string Cliente_lbl_armazenar {
            get {
                return ResourceManager.GetString("Cliente_lbl_armazenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 últimas.
        /// </summary>
        public static string Cliente_lbl_Armazenar_3 {
            get {
                return ResourceManager.GetString("Cliente_lbl_Armazenar_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 últimas.
        /// </summary>
        public static string Cliente_lbl_Armazenar_4 {
            get {
                return ResourceManager.GetString("Cliente_lbl_Armazenar_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 últimas.
        /// </summary>
        public static string Cliente_lbl_Armazenar_5 {
            get {
                return ResourceManager.GetString("Cliente_lbl_Armazenar_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 últimas.
        /// </summary>
        public static string Cliente_lbl_Armazenar_6 {
            get {
                return ResourceManager.GetString("Cliente_lbl_Armazenar_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Armazenar.
        /// </summary>
        public static string Cliente_lbl_Armazenar_nao {
            get {
                return ResourceManager.GetString("Cliente_lbl_Armazenar_nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear acesso após.
        /// </summary>
        public static string Cliente_lbl_Bloquear {
            get {
                return ResourceManager.GetString("Cliente_lbl_Bloquear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 tentativas.
        /// </summary>
        public static string Cliente_lbl_Bloquear_3 {
            get {
                return ResourceManager.GetString("Cliente_lbl_Bloquear_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 tentativas.
        /// </summary>
        public static string Cliente_lbl_Bloquear_4 {
            get {
                return ResourceManager.GetString("Cliente_lbl_Bloquear_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 tentativas.
        /// </summary>
        public static string Cliente_lbl_Bloquear_5 {
            get {
                return ResourceManager.GetString("Cliente_lbl_Bloquear_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Bloquear.
        /// </summary>
        public static string Cliente_lbl_Bloquear_nao {
            get {
                return ResourceManager.GetString("Cliente_lbl_Bloquear_nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string Cliente_lbl_Cliente {
            get {
                return ResourceManager.GetString("Cliente_lbl_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        public static string Cliente_lbl_Contrato {
            get {
                return ResourceManager.GetString("Cliente_lbl_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validade do Contrato.
        /// </summary>
        public static string Cliente_lbl_DataValidade {
            get {
                return ResourceManager.GetString("Cliente_lbl_DataValidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha o Cliente.
        /// </summary>
        public static string Cliente_lbl_Escolha_cliente {
            get {
                return ResourceManager.GetString("Cliente_lbl_Escolha_cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logotipo do Cliente.
        /// </summary>
        public static string Cliente_lbl_Logo {
            get {
                return ResourceManager.GetString("Cliente_lbl_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Cliente.
        /// </summary>
        public static string Cliente_lbl_Nome {
            get {
                return ResourceManager.GetString("Cliente_lbl_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Cliente.
        /// </summary>
        public static string Cliente_lbl_novo_cliente {
            get {
                return ResourceManager.GetString("Cliente_lbl_novo_cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armazenar senhas utilizadas.
        /// </summary>
        public static string Cliente_lbl_placeholder_Armazenar {
            get {
                return ResourceManager.GetString("Cliente_lbl_placeholder_Armazenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear acesso após.
        /// </summary>
        public static string Cliente_lbl_placeholder_Bloquear {
            get {
                return ResourceManager.GetString("Cliente_lbl_placeholder_Bloquear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __/__/____.
        /// </summary>
        public static string Cliente_lbl_placeholder_DataValidade {
            get {
                return ResourceManager.GetString("Cliente_lbl_placeholder_DataValidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o nome do cliente.
        /// </summary>
        public static string Cliente_lbl_placeholder_Nome {
            get {
                return ResourceManager.GetString("Cliente_lbl_placeholder_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar a troca de senha.
        /// </summary>
        public static string Cliente_lbl_placeholder_TrocaSenha {
            get {
                return ResourceManager.GetString("Cliente_lbl_placeholder_TrocaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a URL de acesso.
        /// </summary>
        public static string Cliente_lbl_placeholder_Url {
            get {
                return ResourceManager.GetString("Cliente_lbl_placeholder_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de Cliente.
        /// </summary>
        public static string Cliente_lbl_titulo {
            get {
                return ResourceManager.GetString("Cliente_lbl_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente_lbl_titulo_cliente {
            get {
                return ResourceManager.GetString("Cliente_lbl_titulo_cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar a troca de senha.
        /// </summary>
        public static string Cliente_lbl_TrocaSenha {
            get {
                return ResourceManager.GetString("Cliente_lbl_TrocaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120 dias.
        /// </summary>
        public static string Cliente_lbl_TrocaSenha_120_dias {
            get {
                return ResourceManager.GetString("Cliente_lbl_TrocaSenha_120_dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 dias.
        /// </summary>
        public static string Cliente_lbl_TrocaSenha_30_dias {
            get {
                return ResourceManager.GetString("Cliente_lbl_TrocaSenha_30_dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 dias.
        /// </summary>
        public static string Cliente_lbl_TrocaSenha_60_dias {
            get {
                return ResourceManager.GetString("Cliente_lbl_TrocaSenha_60_dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90 dias.
        /// </summary>
        public static string Cliente_lbl_TrocaSenha_90_dias {
            get {
                return ResourceManager.GetString("Cliente_lbl_TrocaSenha_90_dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Trocar.
        /// </summary>
        public static string Cliente_lbl_TrocaSenha_nao_trocar {
            get {
                return ResourceManager.GetString("Cliente_lbl_TrocaSenha_nao_trocar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL de Acesso.
        /// </summary>
        public static string Cliente_lbl_Url {
            get {
                return ResourceManager.GetString("Cliente_lbl_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente criado com sucesso..
        /// </summary>
        public static string Cliente_msg_criar_valid {
            get {
                return ResourceManager.GetString("Cliente_msg_criar_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente editado com sucesso..
        /// </summary>
        public static string Cliente_msg_editar_valid {
            get {
                return ResourceManager.GetString("Cliente_msg_editar_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente excluido com sucesso..
        /// </summary>
        public static string Cliente_msg_exluir {
            get {
                return ResourceManager.GetString("Cliente_msg_exluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Ativar o cliente?.
        /// </summary>
        public static string Cliente_msg_icone_ativo_ativar {
            get {
                return ResourceManager.GetString("Cliente_msg_icone_ativo_ativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Inativar o cliente?.
        /// </summary>
        public static string Cliente_msg_icone_ativo_inativar {
            get {
                return ResourceManager.GetString("Cliente_msg_icone_ativo_inativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status modificado com sucesso..
        /// </summary>
        public static string Cliente_msg_icone_ativo_valid {
            get {
                return ResourceManager.GetString("Cliente_msg_icone_ativo_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Excluir o cliente?.
        /// </summary>
        public static string Cliente_msg_icone_excluir {
            get {
                return ResourceManager.GetString("Cliente_msg_icone_excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Data de Validade do contrato não pode ser inferior a Data de Hoje.
        /// </summary>
        public static string Cliente_msg_invalid_DataContrato_less_today {
            get {
                return ResourceManager.GetString("Cliente_msg_invalid_DataContrato_less_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id do Cliente é Inválido..
        /// </summary>
        public static string Cliente_msg_not_found_IdCliente {
            get {
                return ResourceManager.GetString("Cliente_msg_not_found_IdCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Armazenar deve ser preenchido.
        /// </summary>
        public static string Cliente_msg_required_Armazenar {
            get {
                return ResourceManager.GetString("Cliente_msg_required_Armazenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na criação de um novo cliente o mesmo deve ser ativo..
        /// </summary>
        public static string Cliente_msg_required_Ativo {
            get {
                return ResourceManager.GetString("Cliente_msg_required_Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obrigatório..
        /// </summary>
        public static string Cliente_msg_required_Bloquear {
            get {
                return ResourceManager.GetString("Cliente_msg_required_Bloquear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Validade do Contrato é obrigatório..
        /// </summary>
        public static string Cliente_msg_required_DataValidade {
            get {
                return ResourceManager.GetString("Cliente_msg_required_DataValidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensão do Logo do Cliente é obrigatória..
        /// </summary>
        public static string Cliente_msg_required_ExtensaoLogo {
            get {
                return ResourceManager.GetString("Cliente_msg_required_ExtensaoLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Logo do Cliente é obrigatório..
        /// </summary>
        public static string Cliente_msg_required_Logo {
            get {
                return ResourceManager.GetString("Cliente_msg_required_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Logo só aceita extensões do tipo &quot;.jpg&quot;, &quot;.png&quot; e &quot;.gif&quot;.
        /// </summary>
        public static string Cliente_msg_required_Logo_extension {
            get {
                return ResourceManager.GetString("Cliente_msg_required_Logo_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do logo do cliente é obrigatório..
        /// </summary>
        public static string Cliente_msg_required_LogoNome {
            get {
                return ResourceManager.GetString("Cliente_msg_required_LogoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome do Cliente deve ter no máximo 60 caracteres..
        /// </summary>
        public static string Cliente_msg_required_maxlength_Nome {
            get {
                return ResourceManager.GetString("Cliente_msg_required_maxlength_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo URL deve ter no máximo 60 caracteres..
        /// </summary>
        public static string Cliente_msg_required_maxlength_Url {
            get {
                return ResourceManager.GetString("Cliente_msg_required_maxlength_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome do Cliente é obrigatório..
        /// </summary>
        public static string Cliente_msg_required_Nome {
            get {
                return ResourceManager.GetString("Cliente_msg_required_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Arquivo do Logo é Obrigatório..
        /// </summary>
        public static string Cliente_msg_required_NomeLogo {
            get {
                return ResourceManager.GetString("Cliente_msg_required_NomeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obrigatório..
        /// </summary>
        public static string Cliente_msg_required_TrocaSenha {
            get {
                return ResourceManager.GetString("Cliente_msg_required_TrocaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo URL de Acesso é obrigatório..
        /// </summary>
        public static string Cliente_msg_required_Url {
            get {
                return ResourceManager.GetString("Cliente_msg_required_Url", resourceCulture);
            }
        }
    }
}
