//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Indicador {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceIndicador {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceIndicador() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Indicador.ResourceIndicador", typeof(ResourceIndicador).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Indicador_lbl_Acoes {
            get {
                return ResourceManager.GetString("Indicador_lbl_Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string Indicador_lbl_Ano {
            get {
                return ResourceManager.GetString("Indicador_lbl_Ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicador.
        /// </summary>
        public static string Indicador_lbl_Indicador {
            get {
                return ResourceManager.GetString("Indicador_lbl_Indicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média Realizada.
        /// </summary>
        public static string Indicador_lbl_media {
            get {
                return ResourceManager.GetString("Indicador_lbl_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média Plano de Vôo.
        /// </summary>
        public static string Indicador_lbl_mediaPlano {
            get {
                return ResourceManager.GetString("Indicador_lbl_mediaPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta.
        /// </summary>
        public static string Indicador_lbl_Meta {
            get {
                return ResourceManager.GetString("Indicador_lbl_Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Indicador.
        /// </summary>
        public static string Indicador_lbl_novo_indicador {
            get {
                return ResourceManager.GetString("Indicador_lbl_novo_indicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetivo.
        /// </summary>
        public static string Indicador_lbl_Objetivo {
            get {
                return ResourceManager.GetString("Indicador_lbl_Objetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodicidade de Análise.
        /// </summary>
        public static string Indicador_lbl_Periodicidade {
            get {
                return ResourceManager.GetString("Indicador_lbl_Periodicidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anual.
        /// </summary>
        public static string Indicador_lbl_Periodicidade_anual {
            get {
                return ResourceManager.GetString("Indicador_lbl_Periodicidade_anual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bimestral.
        /// </summary>
        public static string Indicador_lbl_Periodicidade_bimestral {
            get {
                return ResourceManager.GetString("Indicador_lbl_Periodicidade_bimestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensal.
        /// </summary>
        public static string Indicador_lbl_Periodicidade_mensal {
            get {
                return ResourceManager.GetString("Indicador_lbl_Periodicidade_mensal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestral.
        /// </summary>
        public static string Indicador_lbl_Periodicidade_semestral {
            get {
                return ResourceManager.GetString("Indicador_lbl_Periodicidade_semestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimestral.
        /// </summary>
        public static string Indicador_lbl_Periodicidade_trimestral {
            get {
                return ResourceManager.GetString("Indicador_lbl_Periodicidade_trimestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peridocidade Medição.
        /// </summary>
        public static string Indicador_lbl_PeriodicidadeMedicao {
            get {
                return ResourceManager.GetString("Indicador_lbl_PeriodicidadeMedicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o Ano.
        /// </summary>
        public static string Indicador_lbl_placeholder_Ano {
            get {
                return ResourceManager.GetString("Indicador_lbl_placeholder_Ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o indicador.
        /// </summary>
        public static string Indicador_lbl_placeholder_Indicador {
            get {
                return ResourceManager.GetString("Indicador_lbl_placeholder_Indicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a meta.
        /// </summary>
        public static string Indicador_lbl_placeholder_Meta {
            get {
                return ResourceManager.GetString("Indicador_lbl_placeholder_Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o objetivo deste indicador.
        /// </summary>
        public static string Indicador_lbl_placeholder_Objetivo {
            get {
                return ResourceManager.GetString("Indicador_lbl_placeholder_Objetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a unidade.
        /// </summary>
        public static string Indicador_lbl_placeholder_Unidade {
            get {
                return ResourceManager.GetString("Indicador_lbl_placeholder_Unidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string Indicador_lbl_Processo {
            get {
                return ResourceManager.GetString("Indicador_lbl_Processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        public static string Indicador_lbl_Responsavel {
            get {
                return ResourceManager.GetString("Indicador_lbl_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentido da meta.
        /// </summary>
        public static string Indicador_lbl_Sentido {
            get {
                return ResourceManager.GetString("Indicador_lbl_Sentido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melhor para baixo.
        /// </summary>
        public static string Indicador_lbl_Sentido_dropdown_baixo {
            get {
                return ResourceManager.GetString("Indicador_lbl_Sentido_dropdown_baixo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melhor para cima.
        /// </summary>
        public static string Indicador_lbl_Sentido_dropdown_cima {
            get {
                return ResourceManager.GetString("Indicador_lbl_Sentido_dropdown_cima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicador.
        /// </summary>
        public static string Indicador_lbl_titulo {
            get {
                return ResourceManager.GetString("Indicador_lbl_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano de Voo.
        /// </summary>
        public static string Indicador_lbl_titulo_plano_de_voo {
            get {
                return ResourceManager.GetString("Indicador_lbl_titulo_plano_de_voo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizado.
        /// </summary>
        public static string Indicador_lbl_titulo_realizado {
            get {
                return ResourceManager.GetString("Indicador_lbl_titulo_realizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade.
        /// </summary>
        public static string Indicador_lbl_Unidade {
            get {
                return ResourceManager.GetString("Indicador_lbl_Unidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Deletar este Indicador?.
        /// </summary>
        public static string Indicador_msg_icone_delete {
            get {
                return ResourceManager.GetString("Indicador_msg_icone_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Ano é obrigatório..
        /// </summary>
        public static string Indicador_msg_required_Ano {
            get {
                return ResourceManager.GetString("Indicador_msg_required_Ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Indicador é obrigatório..
        /// </summary>
        public static string Indicador_msg_required_Indicador {
            get {
                return ResourceManager.GetString("Indicador_msg_required_Indicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Meta é obrigatório..
        /// </summary>
        public static string Indicador_msg_required_Meta {
            get {
                return ResourceManager.GetString("Indicador_msg_required_Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite apenas números..
        /// </summary>
        public static string Indicador_msg_required_number_Meta {
            get {
                return ResourceManager.GetString("Indicador_msg_required_number_Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Objetivo é obrigatório..
        /// </summary>
        public static string Indicador_msg_required_Objetivo {
            get {
                return ResourceManager.GetString("Indicador_msg_required_Objetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Periodicidade é obrigatório..
        /// </summary>
        public static string Indicador_msg_required_Periodicidade {
            get {
                return ResourceManager.GetString("Indicador_msg_required_Periodicidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Periodicidade Medição é obrigatório..
        /// </summary>
        public static string Indicador_msg_required_PeriodicidadeMedicao {
            get {
                return ResourceManager.GetString("Indicador_msg_required_PeriodicidadeMedicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório.
        /// </summary>
        public static string Indicador_msg_required_Plano_de_voo {
            get {
                return ResourceManager.GetString("Indicador_msg_required_Plano_de_voo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Processo é obrigatório..
        /// </summary>
        public static string Indicador_msg_required_Processo {
            get {
                return ResourceManager.GetString("Indicador_msg_required_Processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Responsável é obrigatório..
        /// </summary>
        public static string Indicador_msg_required_Responsavel {
            get {
                return ResourceManager.GetString("Indicador_msg_required_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Sentido é obrigatório..
        /// </summary>
        public static string Indicador_msg_required_Sentido {
            get {
                return ResourceManager.GetString("Indicador_msg_required_Sentido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Unidade é obrigatório..
        /// </summary>
        public static string Indicador_msg_required_Unidade {
            get {
                return ResourceManager.GetString("Indicador_msg_required_Unidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicador salvo com sucesso..
        /// </summary>
        public static string Indicador_msg_save_valid {
            get {
                return ResourceManager.GetString("Indicador_msg_save_valid", resourceCulture);
            }
        }
    }
}
