//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Licenca {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceLicenca {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLicenca() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Licenca.ResourceLicenca", typeof(ResourceLicenca).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emissão.
        /// </summary>
        public static string IN_lbl_DtEmissao {
            get {
                return ResourceManager.GetString("IN_lbl_DtEmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Vencimento.
        /// </summary>
        public static string IN_lbl_DtVencimento {
            get {
                return ResourceManager.GetString("IN_lbl_DtVencimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificação.
        /// </summary>
        public static string IN_lbl_Notificacao {
            get {
                return ResourceManager.GetString("IN_lbl_Notificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escreva uma observação.
        /// </summary>
        public static string IN_lbl_Observacao {
            get {
                return ResourceManager.GetString("IN_lbl_Observacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Licenças.
        /// </summary>
        public static string IN_lbl_Panel_Licenca {
            get {
                return ResourceManager.GetString("IN_lbl_Panel_Licenca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o titulo.
        /// </summary>
        public static string IN_lbl_PlaceholderTitulo {
            get {
                return ResourceManager.GetString("IN_lbl_PlaceholderTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string IN_lbl_Processo {
            get {
                return ResourceManager.GetString("IN_lbl_Processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        public static string IN_lbl_Responsavel {
            get {
                return ResourceManager.GetString("IN_lbl_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string IN_lbl_Status {
            get {
                return ResourceManager.GetString("IN_lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo.
        /// </summary>
        public static string IN_lbl_Titulo {
            get {
                return ResourceManager.GetString("IN_lbl_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Licenca.
        /// </summary>
        public static string IN_lbl_titulo_nova_Licenca {
            get {
                return ResourceManager.GetString("IN_lbl_titulo_nova_Licenca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Titulo é obrigatório.
        /// </summary>
        public static string IN_msg_required_Licenca {
            get {
                return ResourceManager.GetString("IN_msg_required_Licenca", resourceCulture);
            }
        }
    }
}
