//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Instrumentos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceInstrumentos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceInstrumentos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Instrumentos.ResourceInstrumentos", typeof(ResourceInstrumentos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data da notificação deve ser maior que a data do registro..
        /// </summary>
        public static string ADataNotificacaoCalibracaoDeveSerMaiorQueADataDoRegistro {
            get {
                return ResourceManager.GetString("ADataNotificacaoCalibracaoDeveSerMaiorQueADataDoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data da notificação deve ser menor que a data da proxima calibração..
        /// </summary>
        public static string ADataNotificacaoCalibracaoDeveSerMenorQueADataDaProximaCalibracao {
            get {
                return ResourceManager.GetString("ADataNotificacaoCalibracaoDeveSerMenorQueADataDaProximaCalibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data da próxima calibração deve ser maior que a data do registro..
        /// </summary>
        public static string ADataProximaCalibracaoDeveSerMaiorQueADataDoRegistro {
            get {
                return ResourceManager.GetString("ADataProximaCalibracaoDeveSerMaiorQueADataDoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculado pelo sistema.
        /// </summary>
        public static string IN_lbl_Calculado_pelo_sistema {
            get {
                return ResourceManager.GetString("IN_lbl_Calculado_pelo_sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir Certificado.
        /// </summary>
        public static string IN_lbl_certificado {
            get {
                return ResourceManager.GetString("IN_lbl_certificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critério de Aceitação.
        /// </summary>
        public static string IN_lbl_Criterio_de_aceitacao {
            get {
                return ResourceManager.GetString("IN_lbl_Criterio_de_aceitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Notificação.
        /// </summary>
        public static string IN_lbl_data_notificacao {
            get {
                return ResourceManager.GetString("IN_lbl_data_notificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Registro.
        /// </summary>
        public static string IN_lbl_data_registro {
            get {
                return ResourceManager.GetString("IN_lbl_data_registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação Criterio.
        /// </summary>
        public static string IN_lbl_DescricaoCriterio {
            get {
                return ResourceManager.GetString("IN_lbl_DescricaoCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Próxima Calibração.
        /// </summary>
        public static string IN_lbl_Dt_proxima_calibracao {
            get {
                return ResourceManager.GetString("IN_lbl_Dt_proxima_calibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string IN_lbl_erro {
            get {
                return ResourceManager.GetString("IN_lbl_erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escala.
        /// </summary>
        public static string IN_lbl_Escala {
            get {
                return ResourceManager.GetString("IN_lbl_Escala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incerteza.
        /// </summary>
        public static string IN_lbl_incerteza {
            get {
                return ResourceManager.GetString("IN_lbl_incerteza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalo.
        /// </summary>
        public static string IN_lbl_intervalo {
            get {
                return ResourceManager.GetString("IN_lbl_intervalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumento.
        /// </summary>
        public static string IN_lbl_Intrumento {
            get {
                return ResourceManager.GetString("IN_lbl_Intrumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local de Uso.
        /// </summary>
        public static string IN_lbl_Local_de_uso {
            get {
                return ResourceManager.GetString("IN_lbl_Local_de_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string IN_lbl_Marca {
            get {
                return ResourceManager.GetString("IN_lbl_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menor Divisão.
        /// </summary>
        public static string IN_lbl_Menos_divisao {
            get {
                return ResourceManager.GetString("IN_lbl_Menos_divisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string IN_lbl_Modelo {
            get {
                return ResourceManager.GetString("IN_lbl_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número do Certificado.
        /// </summary>
        public static string IN_lbl_nm_certificado {
            get {
                return ResourceManager.GetString("IN_lbl_nm_certificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string IN_lbl_Numero {
            get {
                return ResourceManager.GetString("IN_lbl_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações.
        /// </summary>
        public static string IN_lbl_observacoes {
            get {
                return ResourceManager.GetString("IN_lbl_observacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orgão Calibrador.
        /// </summary>
        public static string IN_lbl_orgao_calibrador {
            get {
                return ResourceManager.GetString("IN_lbl_orgao_calibrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros.
        /// </summary>
        public static string IN_lbl_parametros {
            get {
                return ResourceManager.GetString("IN_lbl_parametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir um certificado.
        /// </summary>
        public static string IN_lbl_placeholder_certificado {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_certificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o critério de aceitação.
        /// </summary>
        public static string IN_lbl_placeholder_Criterio_de_aceitacao {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_Criterio_de_aceitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a descrição do critério..
        /// </summary>
        public static string IN_lbl_placeholder_DescricaoCriterio {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_DescricaoCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Notificação.
        /// </summary>
        public static string IN_lbl_placeholder_dt_notificacao {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_dt_notificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Registro.
        /// </summary>
        public static string IN_lbl_placeholder_dt_registro {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_dt_registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a escala.
        /// </summary>
        public static string IN_lbl_placeholder_Escala {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_Escala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o instrumento.
        /// </summary>
        public static string IN_lbl_placeholder_Instrumento {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_Instrumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o local de uso..
        /// </summary>
        public static string IN_lbl_placeholder_Local_de_uso {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_Local_de_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a marca.
        /// </summary>
        public static string IN_lbl_placeholder_Marca {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a menor divisão.
        /// </summary>
        public static string IN_lbl_placeholder_Menor_divisao {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_Menor_divisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o modelo.
        /// </summary>
        public static string IN_lbl_placeholder_Modelo {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o número do certificado.
        /// </summary>
        public static string IN_lbl_placeholder_nm_certificado {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_nm_certificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o número.
        /// </summary>
        public static string IN_lbl_placeholder_Numero {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite algumas observações..
        /// </summary>
        public static string IN_lbl_placeholder_observacoes {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_observacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o orgão calibrador.
        /// </summary>
        public static string IN_lbl_placeholder_orgao_calibrador {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_orgao_calibrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próxima Calibração.
        /// </summary>
        public static string IN_lbl_placeholder_proxima_calibracao {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_proxima_calibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha o responsável.
        /// </summary>
        public static string IN_lbl_placeholder_Responsavel {
            get {
                return ResourceManager.GetString("IN_lbl_placeholder_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próxima Calibração.
        /// </summary>
        public static string IN_lbl_proxima_calibracao {
            get {
                return ResourceManager.GetString("IN_lbl_proxima_calibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        public static string IN_lbl_Responsavel {
            get {
                return ResourceManager.GetString("IN_lbl_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        public static string IN_lbl_resultado {
            get {
                return ResourceManager.GetString("IN_lbl_resultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string IN_lbl_Status {
            get {
                return ResourceManager.GetString("IN_lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrado.
        /// </summary>
        public static string IN_lbl_Status_calibrado {
            get {
                return ResourceManager.GetString("IN_lbl_Status_calibrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Calibração.
        /// </summary>
        public static string IN_lbl_Status_em_calibracao {
            get {
                return ResourceManager.GetString("IN_lbl_Status_em_calibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fora de Uso.
        /// </summary>
        public static string IN_lbl_Status_fora_de_uso {
            get {
                return ResourceManager.GetString("IN_lbl_Status_fora_de_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Calibrado.
        /// </summary>
        public static string IN_lbl_Status_nao_calibrado {
            get {
                return ResourceManager.GetString("IN_lbl_Status_nao_calibrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado.
        /// </summary>
        public static string IN_lbl_tb_aprovado {
            get {
                return ResourceManager.GetString("IN_lbl_tb_aprovado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado Por.
        /// </summary>
        public static string IN_lbl_tb_aprovado_por {
            get {
                return ResourceManager.GetString("IN_lbl_tb_aprovado_por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibração.
        /// </summary>
        public static string IN_lbl_tb_calibracao {
            get {
                return ResourceManager.GetString("IN_lbl_tb_calibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Calibração.
        /// </summary>
        public static string IN_lbl_tb_dt_calibracao {
            get {
                return ResourceManager.GetString("IN_lbl_tb_dt_calibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Calibração.
        /// </summary>
        public static string IN_lbl_tb_nova_calibracao {
            get {
                return ResourceManager.GetString("IN_lbl_tb_nova_calibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Certificado.
        /// </summary>
        public static string IN_lbl_tb_numero_certificado {
            get {
                return ResourceManager.GetString("IN_lbl_tb_numero_certificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações.
        /// </summary>
        public static string IN_lbl_tb_observacoes {
            get {
                return ResourceManager.GetString("IN_lbl_tb_observacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Órgão Calibrador.
        /// </summary>
        public static string IN_lbl_tb_orgao_calibrador {
            get {
                return ResourceManager.GetString("IN_lbl_tb_orgao_calibrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próxima Calibração.
        /// </summary>
        public static string IN_lbl_tb_proxima_calibracao {
            get {
                return ResourceManager.GetString("IN_lbl_tb_proxima_calibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros do Instrumento a Controlar.
        /// </summary>
        public static string IN_lbl_titulo_intrumento_a_controlar {
            get {
                return ResourceManager.GetString("IN_lbl_titulo_intrumento_a_controlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Instrumento.
        /// </summary>
        public static string IN_lbl_titulo_novo_instrumento {
            get {
                return ResourceManager.GetString("IN_lbl_titulo_novo_instrumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros do Instrumento Pós Calibração.
        /// </summary>
        public static string IN_lbl_titulo_pos_calibracao {
            get {
                return ResourceManager.GetString("IN_lbl_titulo_pos_calibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela Calibração.
        /// </summary>
        public static string IN_lbl_titulo_tabela_calibracao {
            get {
                return ResourceManager.GetString("IN_lbl_titulo_tabela_calibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumento criado com sucesso..
        /// </summary>
        public static string IN_msg_create_valid {
            get {
                return ResourceManager.GetString("IN_msg_create_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Calculado pelo Sistema é obrigatório..
        /// </summary>
        public static string IN_msg_required_Calculado_pelo_sistema {
            get {
                return ResourceManager.GetString("IN_msg_required_Calculado_pelo_sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Certificado é obrigatório..
        /// </summary>
        public static string IN_msg_required_certificado {
            get {
                return ResourceManager.GetString("IN_msg_required_certificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Critério de Aceitação é obrigatório..
        /// </summary>
        public static string IN_msg_required_Criterio_de_aceitacao {
            get {
                return ResourceManager.GetString("IN_msg_required_Criterio_de_aceitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aprovador é obrigatório..
        /// </summary>
        public static string IN_msg_required_data_aprovador {
            get {
                return ResourceManager.GetString("IN_msg_required_data_aprovador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de notificação é obrigatória..
        /// </summary>
        public static string IN_msg_required_data_notificacao {
            get {
                return ResourceManager.GetString("IN_msg_required_data_notificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de registro é obrigatória..
        /// </summary>
        public static string IN_msg_required_data_registro {
            get {
                return ResourceManager.GetString("IN_msg_required_data_registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Data da Notificação é obrigatória..
        /// </summary>
        public static string IN_msg_required_dt_notificacao {
            get {
                return ResourceManager.GetString("IN_msg_required_dt_notificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Data Registro é obrigatória..
        /// </summary>
        public static string IN_msg_required_dt_registro {
            get {
                return ResourceManager.GetString("IN_msg_required_dt_registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Escala é obrigatório..
        /// </summary>
        public static string IN_msg_required_Escala {
            get {
                return ResourceManager.GetString("IN_msg_required_Escala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Instrumento é obrigatório..
        /// </summary>
        public static string IN_msg_required_Intrumento {
            get {
                return ResourceManager.GetString("IN_msg_required_Intrumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Local de Uso é obrigatório..
        /// </summary>
        public static string IN_msg_required_Local_de_uso {
            get {
                return ResourceManager.GetString("IN_msg_required_Local_de_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Marca é obrigatório..
        /// </summary>
        public static string IN_msg_required_Marca {
            get {
                return ResourceManager.GetString("IN_msg_required_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Menor divisão é obrigatório..
        /// </summary>
        public static string IN_msg_required_Menor_divisao {
            get {
                return ResourceManager.GetString("IN_msg_required_Menor_divisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Modelo é obrigatório..
        /// </summary>
        public static string IN_msg_required_Modelo {
            get {
                return ResourceManager.GetString("IN_msg_required_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Número do Certificado é obrigatório..
        /// </summary>
        public static string IN_msg_required_nm_certificado {
            get {
                return ResourceManager.GetString("IN_msg_required_nm_certificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite apenas numeros (ex: 0.5).
        /// </summary>
        public static string IN_msg_required_number_Criterio_de_aceitacao {
            get {
                return ResourceManager.GetString("IN_msg_required_number_Criterio_de_aceitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Número é obrigatório..
        /// </summary>
        public static string IN_msg_required_Numero {
            get {
                return ResourceManager.GetString("IN_msg_required_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Observações é obrigatório..
        /// </summary>
        public static string IN_msg_required_observacoes {
            get {
                return ResourceManager.GetString("IN_msg_required_observacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Orgão Calibrador é obrigatório..
        /// </summary>
        public static string IN_msg_required_orgao_calibrador {
            get {
                return ResourceManager.GetString("IN_msg_required_orgao_calibrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Data da Próxima Calibração é obrigatória..
        /// </summary>
        public static string IN_msg_required_proxima_calibracao {
            get {
                return ResourceManager.GetString("IN_msg_required_proxima_calibracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Responsável é obrigatório..
        /// </summary>
        public static string IN_msg_required_Responsavel {
            get {
                return ResourceManager.GetString("IN_msg_required_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumento salvo com sucesso..
        /// </summary>
        public static string IN_msg_save_valid {
            get {
                return ResourceManager.GetString("IN_msg_save_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Instrumento deve ser possuir um uníco registro com o mesmo nome e mesmo número..
        /// </summary>
        public static string IN_Valida_Nome {
            get {
                return ResourceManager.GetString("IN_Valida_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O numero do Instrumento deve ser único..
        /// </summary>
        public static string IN_Valida_Numero {
            get {
                return ResourceManager.GetString("IN_Valida_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo é obrigatório.
        /// </summary>
        public static string OCampoEObrigatorio {
            get {
                return ResourceManager.GetString("OCampoEObrigatorio", resourceCulture);
            }
        }
    }
}
