//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducao.Norma {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceNorma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNorma() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducao.Norma.ResourceNorma", typeof(ResourceNorma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Norma_lbl_codigo {
            get {
                return ResourceManager.GetString("Norma_lbl_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Norma_lbl_item {
            get {
                return ResourceManager.GetString("Norma_lbl_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Norma.
        /// </summary>
        public static string Norma_lbl_nova_norma {
            get {
                return ResourceManager.GetString("Norma_lbl_nova_norma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string Norma_lbl_processo {
            get {
                return ResourceManager.GetString("Norma_lbl_processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Norma_lbl_titulo {
            get {
                return ResourceManager.GetString("Norma_lbl_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norma deletada com sucesso.
        /// </summary>
        public static string Norma_msg_del_valid {
            get {
                return ResourceManager.GetString("Norma_msg_del_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Ativar esta norma?.
        /// </summary>
        public static string Norma_msg_icone_ativo_ativar {
            get {
                return ResourceManager.GetString("Norma_msg_icone_ativo_ativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Inativar esta norma?.
        /// </summary>
        public static string Norma_msg_icone_ativo_inativar {
            get {
                return ResourceManager.GetString("Norma_msg_icone_ativo_inativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status modificado com sucesso..
        /// </summary>
        public static string Norma_msg_icone_ativo_valid {
            get {
                return ResourceManager.GetString("Norma_msg_icone_ativo_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo Excluir esta norma?.
        /// </summary>
        public static string Norma_msg_icone_excluir {
            get {
                return ResourceManager.GetString("Norma_msg_icone_excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possivel excluir pois há uma ou mais Plai vinculada a norma..
        /// </summary>
        public static string Norma_msg_save_canceled {
            get {
                return ResourceManager.GetString("Norma_msg_save_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norma Salva com sucesso.
        /// </summary>
        public static string Norma_msg_save_valid {
            get {
                return ResourceManager.GetString("Norma_msg_save_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Norma_placeholder_codigo {
            get {
                return ResourceManager.GetString("Norma_placeholder_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Norma_placeholder_item {
            get {
                return ResourceManager.GetString("Norma_placeholder_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Norma_placeholder_titulo {
            get {
                return ResourceManager.GetString("Norma_placeholder_titulo", resourceCulture);
            }
        }
    }
}
